### ISSUE TITLE
Timeout waiting on iframe socket on IE9

### ISSUE THREAD

**Issue by tblakey89** [jpillora/xdomain#103]
I have been trying to get a cross domain request to work on IE9 using xdomain, I am getting a "Timeout waiting on iframe socket" error when trying to do the request. I have read through the FAQ and tried to implement the suggestions.

Here is the console log:
xdomain (http://test-hub.blinkpipe.com): proxying request to slave: 'https://test-mycameras.blinkpipe.com'
xdomain (http://test-hub.blinkpipe.com): creating iframe xdomain-a951d1a0
xdomain (http://test-hub.blinkpipe.com): new socket: xdomain-643fe6f0
xdomain (http://test-hub.blinkpipe.com): Timeout waiting on iframe socket

The server side log for the proxy.html shows that the page was created successfully.

A live demo can be seen here: http://test-hub.blinkpipe.com , enter "12345678" into the input

**Comment by jpillora** [comment]
Maybe IE dislikes http -> https. Since you have a `*.blinkpipe.com` certificate, try hosting your master page on https and report back.

**Comment by tblakey89** [comment]
Thanks for the response, I set up the https and I was getting the same console log as shown in the first post.

I noticed that in the IE9 developer tools it had loaded up a forbidframing page in the iframe, after some research and testing, I found it was a problem from my server which was sending a 'X-Frame-Options' header on the proxy.html. By removing that I was able to get it working.

**Comment by jpillora** [comment]
Ah great
