### ISSUE TITLE
Feature: Warning Hooks

### ISSUE THREAD

**Issue by austinpray** [jpillora/xdomain#104]
On ie7/8 it fires an alert error message. Can there be an option to set `xdomain.alert` to show these messages or not? I would rather handle the message myself.

**Comment by jpillora** [comment]
[Currently](https://github.com/jpillora/xdomain/blob/gh-pages/src/xdomain.coffee#L38-L41) XDomain just looks for `console.warn` and if it's not there, it uses `alert`, so as a workaround, you could just define a `warn` function `window.console = { warn: function(){} };` in IE7/8

**Comment by jpillora** [comment]
Will leave this as a feature request for warning hooks

**Comment by austinpray** [comment]
Ah I see. I will go ahead and give that workaround a shot. 

And yes warning hooks would be very useful so I can handle the errors in my standard "flash" dialogs.

**Comment by austinpray** [comment]
:beers: thanks!
