### ISSUE TITLE
https over http

### ISSUE THREAD

**Issue by theseyi** [jpillora/xdomain#105]
Hey @jpillora,

I have a question about your solution's use of iFrames and the postMessage api.
If I have a master that uses a secure protocol but the slave runs on http in the iFrame, will that raise issues with browsers that have issues with running unsecure content on the web page?

Thanks for your help.
Amazing work :)

**Comment by jpillora** [comment]
It can cause issues in some browsers, safest thing to do is to use https
everywhere

**Comment by theseyi** [comment]
Ah, indeed, thanks for the clarification. I didn't see this in the documentation and figured it might be an issue.
