### ISSUE TITLE
rawgit.com link is broken

### ISSUE THREAD

**Issue by bioball** [jpillora/xdomain#106]
Looks like your file got blacklisted :(

http://rawgit.com/jpillora/xdomain/gh-pages/dist/0.6/xdomain.min.js

Maybe try getting it on cdnjs? http://cdnjs.com/

Or, their site says to use this URL
http://cdn.rawgit.com/jpillora/xdomain/gh-pages/dist/0.6/xdomain.min.js

**Comment by jpillora** [comment]
I just clicked the link and it worked, you sure?

**Comment by bioball** [comment]
Yeah, it was blacklisted for like maybe 30 minutes. Wish I took a screenshot of it

**Comment by bioball** [comment]
Ok, it's down again. Screenshot below:

![screen shot 2014-08-19 at 8 38 31 am](https://cloud.githubusercontent.com/assets/4590460/3968468/f2937d56-27b6-11e4-8f31-0aa09728a0cb.png)

**Comment by jpillora** [comment]
Okay we'll swap to https://cdn.rawgit...

Will change the README

Currently out atm though

**Comment by jpillora** [comment]
Fixed
