### ISSUE TITLE
"TypeError: Argument 1 of FormData.constructor is not an object."

### ISSUE THREAD

**Issue by TheDom** [jpillora/xdomain#107]
We are using [Dropzone](http://www.dropzonejs.com) to upload images onto a different domain as `multipart/form-data`.

xdomain on Firefox 24 (on Windows) throws the following error though

```
TypeError: Argument 1 of FormData.constructor is not an object.
```

This occurs on line 221:

```
this.fd = new xhook[FormData](form);
```

It's true, `form` is `undefined` at this point, also on Firefox 31.0 (OS X) but there everything works just fine.

I patched this line to:

```
this.fd = (form ? new xhook[FormData](form) : new xhook[FormData]());
```

Now the upload works but I'm not sure what other consequences this might bring or why this error occurs in the first place (or how it could be avoided).

Any ideas?

**Comment by jpillora** [comment]
Ah yep - that's probably the right fix. Looks like some browsers don't like undefined in there.

**Comment by jpillora** [comment]
Will look into this soon

**Comment by TheDom** [comment]
Thanks!

**Comment by pswai** [comment]
https://github.com/jpillora/xdomain/blob/gh-pages/dist/0.6/xdomain.js#L220 does not seem to have the fix of FF24.

**Comment by jpillora** [comment]
Fixing

**Comment by jpillora** [comment]
Fixed, forgot to rebuild with the new xhook version >.<

**Comment by TheDom** [comment]
Thanks for taking care of this!

**Comment by pswai** [comment]
Great! Thanks :+1:
