### ISSUE TITLE
Problem loading views in angularjs

### ISSUE THREAD

**Issue by wrandall22** [jpillora/xdomain#11]
I'm not sure how much this project intends to support AngularJS, but I have found that, while attempting to use routes/views, the data does not load.

**Comment by jpillora** [comment]
Could you provide an example ?

**Comment by wrandall22** [comment]
Here's a project I put together to try and read something from Amazon AWS.  I'm getting a timeout when trying to read the iframe.  Perhaps I've set it up incorrectly?

https://github.com/wrandall22/test-xdomain

**Comment by jpillora** [comment]
So turns out your `proxy.html` was using a `data-master` attribute and I was only looking for `master`. Since it actually is a data attribute, I just updated XDomain to allow for them too.
