### ISSUE TITLE
does xdomain support all standard http method?

### ISSUE THREAD

**Issue by feitian124** [jpillora/xdomain#111]
i'm using ember and facing cors problems, since we need support ie8 and its limited support to only `get`, `post` become a pain for us.
does xdomain resloved this? i mean it suppory all standard http methods like `put`, `delete`? thanks.

**Comment by jpillora** [comment]
XDomain supports what XMLHttpRequest supports. So IE8 XHR can’t do PATCH,
though PUT and DELETE should be fine.

**Comment by feitian124** [comment]
understand, thanks.
