### ISSUE TITLE
setTimeout with parameters in IE8 ?

### ISSUE THREAD

**Issue by doubret** [jpillora/xdomain#112]
I have some troubles getting xdomain.js working on IE8.
The context :
- i'm working on an AngularJS application with a flash fallback for uploading files in IE8 & IE9.
- i'm using CORS in all browsers except IE8 & IE9 where i'm using xdomain.js
- it works with IE9 but not with IE8

On IE8, the file is correctly updloaded but the caller is never notified that the upload ended. When i refresh the page, as the file was correctly uploaded, it apears without problem.

I looked through the xdomain.js code, and i noticed the call to setTimeout(check). check is a function with arguments, i'm not sure if IE8 supports setTimeout with this sort of function. Do you think it can be a problem ?

Thanks.

**Comment by jpillora** [comment]
IE89 definitely has `setTimeout`. The problem is that XDomain doesn't work with Flash. See https://github.com/jpillora/xdomain/issues/74#issuecomment-45627062 for IE8,9 upload issues

**Comment by doubret** [comment]
Sorry i didn't get time to investigate more but i found that it was not a setTimeout problem.
Thank you for taking time to reply.
