### ISSUE TITLE
Safari iframe blocks session creation

### ISSUE THREAD

**Issue by clicktrend** [jpillora/xdomain#114]
I faced the problem that Safari blocks creation of session through iframe. Cookie information do not reach the iframe page. Therefore no session use possible. 

Here is a (pseudo) workaround may help understanding the problem http://measurablewins.gregjxn.com/2014/02/safari-setting-third-party-iframe.html

**Comment by jpillora** [comment]
Blocking of 3rd party cookies is indeed a problem, and passing information through the URL is quite hacky.  #89 attempts to solve this with the ability to set master and slave cookie headers, which then must be converted back to `Cookie` on the server, depending on which domain you're interested in.
