### ISSUE TITLE
Re-using same XHR object for multiple requests doesn't work

### ISSUE THREAD

**Issue by Blasz** [jpillora/xdomain#120]
Vanilla xhr allows you to reuse the same xhr object for multiple requests, xdomain breaks this piece of functionality.

**Comment by jpillora** [comment]
I thought I replied to this one...

Interesting, didn't even know that was a thing. What's the benefit of using the same xhr object more than once? I've marked this as a bug as it should be supported by XHook.

**Comment by Blasz** [comment]
Sorry, I created an issue for both xdomain and xhook.

I'm not quite sure what the benefit is, I assume to minimise memory consumption when making a lot of synchronous requests. Regardless, some libraries use xhr objects this way such as https://github.com/scottjehl/Respond
