### ISSUE TITLE
Support for get binary files.

### ISSUE THREAD

**Issue by jarvigames** [jpillora/xdomain#122]
Hi Jamie,

First, sorry for my english, I do not speak very well.

I've been using XDomain about a year ago and now trying to get from Amazon S3 images and binary files such as Blob, but Firefox crashes when trying to send Blob via PostMessage.

I thought this would be fixed in the latest version given as indicated in https://github.com/jpillora/xdomain/issues/36, but after having done a review, I noticed that the only way to send implementaste Blobs from the master to slave but not otherwise.

I have solved this in my application performing simple moficaciones in the library, using the functions you added to send Blobs from the master to the slave, but I consider it better than you what you modify a version next, because I know you'll do better than I.

Thanks for your work, is simply excellent.

**Comment by jpillora** [comment]
Hi @garusisboe we've got an issue already created for adding support for `Blob`s, see #119
