### ISSUE TITLE
Can x-domain support multiple slaves?

### ISSUE THREAD

**Issue by beegeok** [jpillora/xdomain#123]
I would like to call to slave URL with multiple domains, www.abc.com.*. How can I achieve this by using x-domain?

<--script src="http://www.xyz.com/xdomain.min.js" slave="http://www.abc.com.*/proxy.html"></script>

**Comment by jpillora** [comment]
It can, see the API section of the docs for xdomain.slaves()

**Comment by jpillora** [comment]
https://github.com/jpillora/xdomain#using-multiple-masters-and-slaves
