### ISSUE TITLE
Bug: Distribution directory should not contain version numbers (use git tags instead)

### ISSUE THREAD

**Issue by Soviut** [jpillora/xdomain#124]
When I install xdomain via bower `bower install xdomain --save` the dist folder contains several versioned subfolders. The benefit of bower is being able to ignore the version number when sourcing components and instead rely on the bower.json file to manage versions. Having `/dist/0.6/` in my path  means I'm now locked to 0.6 unless I manually edit my source.

I propose a set of unminified and minified dist files that have no version number associated with them and are in the root of the `/dist` folder. Additionally, bower should ignore all the versioned folders.

**Comment by jpillora** [comment]
Correct, there should be no 0.6 sub dir, that was an artifact from a time
when I stored multiple versions at git HEAD. I should instead reference tagged
commits for older versions - as bower does.
