### ISSUE TITLE
Works from CDN but not self-hosted

### ISSUE THREAD

**Issue by soncodi** [jpillora/xdomain#127]
I'm using xdomain only for IE8-9. It works perfectly with the CDN code from the quickstart, but fails when I try to host my own. I only changed the `src=""` on the master and slave `<script>` tags to point to my CDN instead of the rawgit links you provided.

I've checked the paths; the library loads correctly on the master before attempting to make an API call to the slave, but then I get the standard `Access Denied` error from IE. Is there anything special needed (headers, etc..) to host my own copy?

**Comment by jpillora** [comment]
No special headers should be needed. You could compare the headers Rawgit is serving vs your webserver? If you can't see any difference, maybe you need `type="text/javascript"`, though I left it out as I thought this was only required for IE5-6... If it's not that, are you sure your webserver is serving the same file? Can you compare them? If it's also not that, you'll need to create a live demo somewhere so I can debug further

**Comment by soncodi** [comment]
The problem was that I renamed the script, not realizing the script looks for `/xdomain/` while bootstrapping itself. Renaming the script back to `xdomain.js` fixed this issue.

**Comment by jpillora** [comment]
Ahhh yesss, it does when using the attribute API
