### ISSUE TITLE
Older versions of ie (<10) sometimes report error "The data necessary to complete this operation is not yet available"

### ISSUE THREAD

**Issue by jkeys089** [jpillora/xdomain#13]
I found a fix here: http://stackoverflow.com/a/4926780/220825

I'm not a coffee scripter but altering [line 216](https://github.com/jpillora/xdomain/blob/gh-pages/dist/0.5/xdomain.js#L216) of the resulting JS fixed the issue for me.

``` javascript
if (xhr[READY_STATE] === 2) {
```

becomes

``` javascript
if ((typeof(xhr.status) != 'unknown') && xhr[READY_STATE] === 2) {
```

**Comment by jpillora** [comment]
Thanks will take a look soon

**Comment by jpillora** [comment]
pushed a fix, couldn't test though, in progress of adding automated tests on testling
