### ISSUE TITLE
Bug: Preloading images causes XMLHttpRequest TypeError.

### ISSUE THREAD

**Issue by dannycampa** [jpillora/xdomain#136]
Hello, 

First I'd like to say your plugin saves our people a lot of time.

I'm having an issue with 0.6.17 when I try to preload some PNG images.

```
Uncaught InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').
```

Over on line 298:

```
readBody = function() {
    if ('responseText' in xhr) {
      response.text = xhr.responseText;
    }
    if ('responseXML' in xhr) {
      response.xml = xhr.responseXML;
    }
    if ('response' in xhr) {
      response.data = xhr.response;
    }
  };
```

I'm assuming you just need to add a condition inside to look for an arraybuffer instead of text.

Please let me know if this is enough information for you to take care of this. If you need to see it in action I'll need to set up a staging area for you to see it. I rolled back to 0.6.15 on my production site to resolve the issue for now.

Thanks again for your work!

**Comment by jpillora** [comment]
Thanks for the bug report, will take a look into it soon

**Comment by jpillora** [comment]
Merging across from XHook into XDomain now...
