### ISSUE TITLE
Bug: Preflight OPTIONS Request When Unnecessary

### ISSUE THREAD

**Issue by sgarbesi** [jpillora/xdomain#137]
**Please see this plnkr example:**

http://plnkr.co/edit/9YfiPAKo0yagfLhYRmSu

If you remove the `<script>` include for the xdomain.js library there's no preflight OPTIONS request necessary. Something with the library is triggering/enforcing it, even when it's not needed.

**Comment by jpillora** [comment]
I can't see the proxy file in your example?

**Comment by sgarbesi** [comment]
@jpillora Even without the proxy it shouldn't force the options request?

**Comment by jpillora** [comment]
Confirmed this is a bug, though it's not with XDomain, it's with XHook. Still not sure why it's happening.

**Comment by jpillora** [comment]
Created smaller example here http://plnkr.co/edit/5qtYBpBE4GEJlViL6iCH?p=preview

**Comment by kawazoe** [comment]
This issue is causing some requests to fail with a CORS error on firefox. For instance, querying the [geonames api](http://api.geonames.org/countryInfoJSON?username=demo) fails even though the preflight returns a 200. You can try it simply by replacing the url in your plnkr to use any of geonames api. The same request works fine on chrome.

**Comment by sgarbesi** [comment]
@kawazoe As a personal solution, I simply excluded the library unless the browser <= IE9

**Comment by gscottolson** [comment]
Thanks for the awesome work on xdomain/xhook, @jpillora.

We are [seeing this preflighting issue](https://mix.fiftythree.com/), too. In our case, we xdomain/xhook is forcing preflighting for the two calls to `api.segment.io`. When removing xdomain from the page, the calls complete as simple `POST`s.

cc @aseemk @tarajane @gasi

**Comment by jpillora** [comment]
Finally found the time to track down this bug, adding a upload progress listener `xhr.upload.onload = function() {};` always causes an OPTIONS for some reason... So to fix it, I'll just proxy those events which have listeners. Fix should land soon
