### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by bnetter** [jpillora/xdomain#145]
Hey,

`//jpillora.com/xdomain/dist/xdomain.min.js` is not responding anymore. What's wrong?

**Comment by jpillora** [comment]
That's no good, please use the version locked one (rawgit) until I can fix
it, thanks for reporting

**Comment by jpillora** [comment]
Was a DNS issue, it's fixed though DNS still needs to propagate

**Comment by bnetter** [comment]
Good. Thanks !
