### ISSUE TITLE
 can Xdomain solve IE9 "Access is denied" "number -2147024891"?

### ISSUE THREAD

**Issue by cethak89** [jpillora/xdomain#153]
Angular.js app is taking error like in this link. Can xdomain solve this problem? Cause i find an answer in stackoverflow pointing your package.

https://cloud.githubusercontent.com/assets/5298772/7878863/92c6cbc8-05f3-11e5-9788-32f396699cb4.png

Thanks

**Comment by jpillora** [comment]
Yes
