### ISSUE TITLE
Can We Use Wildcard in URL?

### ISSUE THREAD

**Issue by darrindickey** [jpillora/xdomain#166]
Is is possible to use wildcards in domain when declaring master and slave? We serve multiple versions of our app from a main domain.

**Comment by jpillora** [comment]
Wildcards work for declaring masters (slaves can allow any number of domains to proxy through them) though wildcards don't work for declaring slaves (since each slave, each different domain must have its own `proxy.html`). It would be possible though it's not implemented yet.

**Comment by ganeshbuddy** [comment]
@jpillora Is it possible to use now?
