### ISSUE TITLE
HTTP Intranet to HTTPS Internet on IE9 - no cookies being sent

### ISSUE THREAD

**Issue by dmarlow** [jpillora/xdomain#168]
The scenario is as follows. The user visits the intranet site and a check for authentication is made against the internet site. Upon the internet site returning 401 a dialog is displayed notifying that the user isn't authenticated. The user goes to the internet site and logs in. The intranet site isn't able to pick up the internet site's cookies to send in the subsequent checks for authentication. Is this a known issue?

Thanks!

**Comment by jpillora** [comment]
Check out https://github.com/jpillora/xdomain#xdomaincookies
