### ISSUE TITLE
Failed to parse absolute url error

### ISSUE THREAD

**Issue by henryruhs** [jpillora/xdomain#173]
Failed to parse relative url to files <code>data/test.json</code> with version 0.7.3.

Here comes some debug code from the IE9 console:

<pre>
>>> location.protocol
"https:"

>>> xdomain.parseUrl('data/test.json');
LOG: xdomain (https://this-is-my-slave-url): failed to parse absolute url: data/test.json

>>> xdomain.parseUrl('/data/test.json');
LOG: xdomain (https://this-is-my-slave-url): failed to parse absolute url: /data/test.json

>>> xdomain.parseUrl('//data/test.json');
{
   origin : "https://data",
   path : "test.json"
}
</pre>

**Comment by henryruhs** [comment]
I fixed a couple of certificate errors. This magically fixed my xdomain integration.

Maby <code>parseUrl()</code> fails on invalid certificates? Can you confirm that?

**Comment by jpillora** [comment]
Interesting bug, maybe it failed to convert a protocoless scheme to httpa
and so it just left it as //

Good ol IE :)

**Comment by henryruhs** [comment]
My team needs a fix for that, can we give you a helpful hand? Please suggest where to start?

**Comment by jpillora** [comment]
Still occurring after you've fixed your certificates?

**Comment by henryruhs** [comment]
I fixed the certificates but some AJAX requests to local based services / relative urls cause a crash of the Javascript by xdomain because of the parse error.

**Comment by jpillora** [comment]
it shouldn't be crashing, it should just log a message

https://github.com/jpillora/xdomain/blob/gh-pages/dist/xdomain.js#L1044-L1054

and it shouldn't even appear unless you have debug mode on

https://github.com/jpillora/xdomain/blob/gh-pages/dist/xdomain.js#L1009

parseUrl should fail on relative URLs as relative URLs are same domain and
XDomain can ignore them. aside from the failed to parse error, what's
actually going wrong?
