### ISSUE TITLE
'Slaves must be in an iframe' and 'blocked request from' errors - IE9

### ISSUE THREAD

**Issue by zorzysty** [jpillora/xdomain#174]
In my app I have this error on IE9:
`xdomain (http://myapi.com): blocked request from: myapp.com'`
And when running proxy.html
`xdomain (http:/myapi.com): slaves must be in an iframe` 

Here's my app code:

```
<!--[if lte IE 9]>
<script src="xdomain.js"></script>
<script>
    xdomain.slaves({
        'http://myapi.com': '/some_folder/proxy.html'
    });
</script>
<![endif]-->
```

And here's proxy.html:

```
<!DOCTYPE html>
<script src="xdomain.js"></script>
<script>
    xdomain.masters({
        "http://myapp.com/": "*"
    });
</script>
```

**x-frame-options** header is **not** listed in proxy.html or xdomain.js http response. Also xdomain.js is loaded before any other script.
What could be wrong?

**Comment by zdenekhatak** [comment]
Having the exactly same problem.

**Comment by zdenekhatak** [comment]
This could be the solution https://github.com/jpillora/xdomain/issues/25
Unfortunately, I'm not able to try it right now.

**Comment by jpillora** [comment]
Hmm that's strange, could you please make a small demo which reproduces your issue (like this one http://jpillora.com/xdomain/)? You can post the link here or email me dev@jpillora.com
