### ISSUE TITLE
Problem with Adobe Experience Manager + Internet Explorer + xdomain

### ISSUE THREAD

**Issue by tombebombe** [jpillora/xdomain#179]
Hello again,

another year, another problem...

Adobe Experience Manager is a CMS that recently introduced (or updated) a script to block cross site request forgeries and such.
This script tempers with the standard XMLHttpRequest, which seems to interfere with xdomain.js in IE9+ (Chrome and FF run just fine)
Before that script was introduced/updated, everything worked fine.

The debug log stops after creating the iFrame:
 xdomain ($Master$): adding slave: $Slave$ 
 xdomain ($Master$): proxying request to slave: '$Slave$' 
 xdomain ($Master$): creating iframe xdomain-6b637324 

Because of the nature of the CMS, we don't really have the option to load xdomain.js before the built-in JavaScript files. 
However, if we do that via Fiddler, it does not work in Chrome and FF, too:
xdomain ($Master$): adding slave: $Slave$
xdomain.js:1022 xdomain ($Master$): proxying request to slave: '$Slave$'
xdomain.js:1022 xdomain ($Master$): creating iframe xdomain-66e3e090
xdomain.js:1022 xdomain ($Master$): new socket: xdomain-7eb6734e
xdomain.js:1022 xdomain ($Slave$): new socket: xdomain-7eb6734e
xdomain.js:1022 xdomain ($Slave$): slave listening for requests on socket: xdomain-7eb6734e
xdomain.js:1022 xdomain ($Slave$): receive socket: xdomain-7eb6734e: XD_CHECK
xdomain.js:1022 xdomain ($Slave$): send socket: xdomain-7eb6734e: ready
xdomain.js:1022 xdomain ($Slave$): ready socket: xdomain-7eb6734e (emit #0 pending)
148xdomain.js:1022 xdomain ($Slave$): receive socket: xdomain-7eb6734e: XD_CHECK
xdomain.js:1022 xdomain ($Master$): Timeout waiting on iframe socket
xdomain.js:1022 xdomain ($Slave$): receive socket: xdomain-7eb6734e: XD_CHECK

The error in IE is still the same with xdomain.js loaded before everything else.

We created a testpage in AEM where you should be able to reproduce the error:
https://eloqua.publicis.de/content/geometrixx/en/eloquapage.nocache.html

Could you please have a look at this?

Thanks in advance,
tombe

**Comment by tombebombe** [comment]
Update:
The problem is not really related to xdomain, xdomain just triggers it when attaching the iFrame.

The problem lies in clientlibs_jquery.js (http://eloqua.publicis.de/etc/designs/geometrixx/clientlibs_jquery.js). The same code can also be found in granite.js, which, as far as i know, is a default component of Adobe Experience Manager, and probably was just renamed in the test case (The AEM servers are managed by a third party, i am only using them).
Here, Node.appendChild is overriden and accesses contentWindow.document of the iframe, which is not possible in IE:
line 11976:
    if (window.Node) {
        var ac = Node.prototype.appendChild;
        Node.prototype.appendChild = function() {
            var result = ac.apply(this, arguments);
            if (result.nodeName === 'IFRAME') {
                if (result.contentWindow && !result._csrf) {
                    result._csrf = true;
                    handleForm(result.contentWindow.document);
                }
            }
            return result;
        };
    }

I have found two ways to circumvent this issue. 

The first solution is rather simple:
In the method getFrame in xdomain.js, just add
frame._csrf = true;

The other solution is to use replaceChild instead of appendChild:
getFrame = function(origin, proxyPath) {
  var frame;  
  var replacerId;

  if (frames[origin]) {
    return frames[origin];
  }
  frame = document.createElement("iframe");
  replacerId = frame.id = frame.name = guid();
  log("creating iframe " + frame.id);
  frame.src = "" + origin + proxyPath;
  frame.setAttribute('style', 'display:none;');

  var targetDiv = document.createElement('DIV');
  targetDiv.id = replacerId;  
  document.body.appendChild(targetDiv);

  var replaceElement = document.getElementById(replacerId);
  document.body.replaceChild(frame, replaceElement);
  return frames[origin] = frame.contentWindow;
};

So far, both seem to be working like a charm, but i have yet to test it outside of a simple test case.
I guess the first approach is cleaner. Do you see any issues with any of them?

Anyways, this is not really xdomain-related, so i guess you can close the issue.
However, as this post here is the only search result i got when googling the problem, i thought posting my solution to be relevant.

Regards,
tombe

**Comment by jpillora** [comment]
Thanks for the update tombe
