### ISSUE TITLE
Android 4.1.2 Incompatible

### ISSUE THREAD

**Issue by NathanWalker** [jpillora/xdomain#19]
I'll provide more details and a stacktrace when I can but ran into this today. Had to remove xdomain to get Droid 4.1.2 to work at all. (Jelly Bean native browser)

**Comment by odino** [comment]
I think we've also bumped into this problem these days, would be very interested in seeing what's actually wrong. 

@NathanWalker, the stacktrace would be terrific :)

**Comment by jpillora** [comment]
@NathanWalker Interesting... check if XHook is working here http://jpillora.com/xhook, if it is working, then maybe it could be  `postMessage` related?

**Comment by odino** [comment]
@jpillora this is what happens from the S3 native browser:

![screenshot_2013-10-25-04-30-22](https://f.cloud.github.com/assets/328420/1404642/6e41124c-3d0c-11e3-8c35-6fc94fafb18e.png)

**Comment by jpillora** [comment]
@odino Ah ha, so XHook isn't working on android. That's the problem. Can you get a stack trace?

**Comment by odino** [comment]
It's a pity you cant deploy xdomain due to restrictions here but we will try to investigate, as this is a pretty nasty showstopper. Have you had the chance to look at the issue? Will try to provide more infos as soon as we get them!

**Comment by odino** [comment]
Here you have a stacktrace:

![screenshot_2013-10-28-16-51-24](https://f.cloud.github.com/assets/328420/1419606/c4735f38-3fcf-11e3-860e-f0474c20eb24.png)

**Comment by jpillora** [comment]
I have reports that it now works on old Safari and Android, reopen if necessary :)

**Comment by NathanWalker** [comment]
Awesome Jaime, thanks!!
