### ISSUE TITLE
xhook/xdomain support for XHR#abort()

### ISSUE THREAD

**Issue by stevenyxu** [jpillora/xdomain#20]
I'm using XDomain here with success, so thanks for the work! I've contributed a couple of bugfixes to the projects in the past, so thanks for your attention on those.

I'm running into an issue that seems like it involves a more sophisticated fix. I'm working on it now/soon but wanted to bounce the general problem and approach off you to see if you had any thoughts.

Specifically, in XDomain xhr.abort() doesn't do anything. `transiting` is never set to true if the before hook exists (as it does in XDomain), so no XHR is aborted. This has presented a specific problem for us in our app since we call xhr.abort() in a cleanup process that includes dereferencing the xhr. That, combined with the way the EventEmitter works, makes it so that the final success and state change callbacks still get called, which produces a null reference way down the line in our app. We could patch it up at many levels in our app or at the surface level in XHook (for instance, making the facade's abort function remove the success hooks), but I'm interested in a deeper fix that actually implements abort. Due to the asynchronous nature of postMessage, it probably won't be perfect, but it feels more "right".

The approach I'm examining is to add a new `window.xhook` function (alongside `before` and `after`), for instance `abort`, that basically intercepts `window.XMLHttpRequest.prototype.abort` the way that `before` intercepts `window.XMLHttpRequest.prototype.send`. Then implement the `abort` method in XDomain to post some new message structure (`send` produces something like `{"id":"000","msg":{...}}`, so maybe something like `{"id":"000","action":"abort"}`). If I had setupReceiver on the proxy page include some dictionary of ongoing requests, we could just listen for that sort of message and abort accordingly. If that all sounds kosher to you, I'd be happy to put in the dev work to make it happen.

**Comment by jpillora** [comment]
Hi Steven, I was looking into implementing an event proxy for XDomain (passes function calls over and events back with `postMessage` similar to your solution, however this would cover all events). XHook will need `on(method)` and `trigger(event)` methods on the [request object](https://github.com/jpillora/xhook#request-object) first, then the rest should be in XDomain. Since it's not a big change, I'll try and find some time to implement this tonight. Edit: Needs to pass over function calls.

**Comment by jpillora** [comment]
yes, this is partially complete https://github.com/jpillora/xhook/tree/feature-hook-events needs to finished and merged into xdomain still, been swamped with work though :(

**Comment by jpillora** [comment]
Fixed with the release of 0.6 :) https://github.com/jpillora/xdomain#download
