### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by bensquire** [jpillora/xdomain#22]
I'm sure I'm just being a newb, but could we see an example of the HTML required on the master node to multiple slaves. Each of my attempts so far has just resulted in access denied errors. Putting it in the script tag (only 1 slave) worked first time.

Thanks in advance!
Ben

P.S For example

```
     <!--[if lte IE 10]>
     <script src="http://jpillora.com/xdomain/dist/0.5/xdomain.min.js"></script>
     <script>
         xdomain({
             slaves: {
                 'http://dev.api.example.com/proxy.html': 'proxy.html',
                 'http://dev.api.example2.com/proxy.html': 'proxy.html',
             }
         });
     </script>
     <![endif]-->
```

**Comment by jpillora** [comment]
Hi Ben, in your slave object, the keys should be the origin (protocol+host)
and the values should be the path to a proxy file, so just remove the
/proxy.html from the keys. ill add code that'll display an error, I think
it's silently ignoring it at the moment

On Friday, November 22, 2013, Ben Squire wrote:

> I'm sure I'm just being a newb, but could we see an example of the HTML
> required on the master node to with multiple slaves. Each of my attempts so
> far has just resulted in access denied errors. Putting it in the script tag
> (only 1 slave) worked first time.
> 
> Thanks in advance!
> Ben
> 
> P.S For example
> 
> ```
>  
> ```
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jpillora/xdomain/issues/22
> .

## 

Cheers
Jaime

**Comment by jpillora** [comment]
https://github.com/jpillora/xdomain#slaves
