### ISSUE TITLE
Loses xhr onprogress events

### ISSUE THREAD

**Issue by ghost** [jpillora/xdomain#23]
xdomain does not proxy(?) the XMLHttpRequest progress events. None of the following work.

```
    var xhr = new XMLHttpRequest();

    xhr.upload.onprogress = function (e) {
        ...
    };

    xhr.progress = function (e) {
        ...
    };

    xhr.addEventListener('progress', function (e) {
        ...
    });
```

**Comment by jpillora** [comment]
It does not proxy events yet. Trying to find the time still... This is actually an XHook issue (which has already been created  https://github.com/jpillora/xhook/issues/6). XHook only provides the means to modify the request and response. Feel free to contribute though :)

**Comment by ghost** [comment]
Ok, cool. As an aside, maybe xdomain could expose the original XMLHttpRequest object?

**Comment by jpillora** [comment]
Yup that's another XHook thing though

**Comment by ghost** [comment]
Added a quick and dirty implementation to my fork - https://github.com/DveMac/xhook
