### ISSUE TITLE
Invalid character in xdomain.js

### ISSUE THREAD

**Issue by AyhamAlzoubi** [jpillora/xdomain#24]
i have syntax error in  xdomain.js line 1 character 4727, 
and then giving error: SCRIPT5022: timeout connecting to iframe

**Comment by odino** [comment]
@AyhamAlzoubi I think you are minifying JS thats why you see a syntax error at char **4727**

You should try to find out where the real error is, in the non-minified source

**Comment by hades200082** [comment]
I'm getting this error too.  Surely xdomain should work with minified javascript since 99.99% of all production websites will minify?

**Comment by jpillora** [comment]
What version are you using?
