### ISSUE TITLE
blocked request

### ISSUE THREAD

**Issue by serafinomb** [jpillora/xdomain#25]
I think I've everything set up just right but I get this message:

> xdomain (http://slave-url.com): blocked request from: 'http://master-url.com' 

and on slave domain on load I get this:

> xdomain (http://slave-url.com): slaves must be in an iframe

Have anyone any idea of what's causing the issue?

**Comment by serafinomb** [comment]
Solved by adding this:

> Header add Access-Control-Allow-Origin "*"
> Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
> Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"

In the Slave .htaccess.

**Comment by jpillora** [comment]
Blocked means you've misconfugured it somehow

You haven't actually fixed it, you're just using cors now. You can use cors
if you like but you won't have easy IE support.

If you want to use XDomain, can you post your code? Script tags used?

**Comment by serafinomb** [comment]
I've noticed an iframe in the master-site and no errors a few ago..
Tried to remove the .htaccess lines and indeed it's working fine with no errors.

I've used the same code shown in the Quick Usage.

**Comment by jpillora** [comment]
Okay good to hear. Yup the quick usage code should do it.

**Comment by pasupulaphani** [comment]
I'm now facing this error. How did you solve this exactly?

**Comment by pasupulaphani** [comment]
This worked for me:
proxy.html

```
<!doctype html>
<script src=" * path to script here * /xdomain.min.js" data-master="*"></script>
```

In index.html

```
<script src=" * path to script here * /xdomain.min.js"></script>
<script>
  xdomain.slaves({
    'http://www.example.co.uk': '/proxy.html'
  });
</script>
```

**Comment by c0mrade** [comment]
Solution to this is very misleading. And I mean both by @Blueowner and @pasupulaphani . Solution is to turn off the 'X-Frame-Options' header for the proxy.html

**Comment by pasupulaphani** [comment]
Thank you very much @c0mrade . I will try what u said and will edit my above comment.

**Comment by jpmckearin** [comment]
@c0mrade Can you elaborate on what you mean by "turn off" the X-Frame-Options header? Looking at the [specs for X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options) state that the only options are DENY, SAMEORIGIN, and ALLOW-FROM uri. Could you follow up as well, @pasupulaphani

**Comment by c0mrade** [comment]
means remove it
