### ISSUE TITLE
Does it use PostMessage API for every xhr request or just cross domain?

### ISSUE THREAD

**Issue by codef0rmer** [jpillora/xdomain#26]
I want to enable xdomain XHR for requests happening cross-domain only. For all other XHR request (for same domain) should work without PostMessage.

Is it possible?

**Comment by jpillora** [comment]
Currently [XHook](https://github.com/jpillora/xhook) will replace every XHR with an XHook XHR, however, only requests with a **matching slave domain** are actually sent through the postMessage proxy.

The XHook XHR doesn't completely implement XHR2 yet, though it's currently in progress.

Have you run into a problem or are you just determining behaviour?

**Comment by codef0rmer** [comment]
I'm planning to use it so this thought came to my mind. So are you saying if a master domain matches with the slave then only xdomain will trigger?

**Comment by jpillora** [comment]
If a master has a slave that matches a request, XDomain will send it to
that slave.

Then the slave checks that the master domain is allowed to use it. Though I
think you only care about the first part.

**Comment by codef0rmer** [comment]
Thanks for the quick reply, you are awesome.

Yes. I'm concerned about following 2 scenarios (lets say an app domain is foo.com):
1. XHRing bar.com or bar.foo.com - XDOMAIN will trigger
2. XHRing ./getUsers (on foo.com) - XDOMAIN will not trigger

Correct?

**Comment by jpillora** [comment]
Correct. Just don't include a slave for foo.com
