### ISSUE TITLE
Troubleshooting IE8/9

### ISSUE THREAD

**Issue by andylockran** [jpillora/xdomain#27]
This is more a 'FYI' that maybe should be appended to the README.md

When you run xdomain in IE8/9 - you must properly declare the Doctype at the top of your HTML, else IE8/9 will run the page in quirks mode which breaks JSON compatibility for IE.

Whilst this manifests itself nicely, unfortunately IE9 then throws the error 'console not defined' in xdomain.min.js - removing the two references to console correctly pop's up the alert box that says 'Your browser does not support JSON'.

**Comment by jpillora** [comment]
https://github.com/jpillora/xdomain#internet-explorer though will fix the console error

**Comment by andylockran** [comment]
Thank you.

**Comment by RishikeshDarandale** [comment]
http://jpillora.com/xdomain/ example doesn't work with IE8 and gives above error. Can you please let me know what is missing?
![xdomain](https://cloud.githubusercontent.com/assets/4144769/9007377/2f9895c6-37ae-11e5-8dcb-abf47428e999.png)

**Comment by jpillora** [comment]
You need the html 5 doc type I think

**Comment by igodzp** [comment]
But your example (demo) already has it up there. Could you please check if the demo is currently working in IE8? Thanks!
