### ISSUE TITLE
Issue with X-Frame-Options ?

### ISSUE THREAD

**Issue by brandonparsons** [jpillora/xdomain#28]
When loading up the script from my master domain (the one making AJAX requests), received the following error in the JS console:

`Refused to display 'http://localhost:3000/proxy.html' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`

Is this an issue with my server configuration?

**Comment by jpillora** [comment]
What server is behind `http://localhost:3000/` ? I'm guessing you have a security module or something running thats adding the `X-Frame-Options` header. To make XDomain work with `X-Frame-Options`, you'll also need to allow your  master domain the load the slave domain. Edit: Just checked and `ALLOW-FROM` isn't supported by many browsers: http://erlend.oftedal.no/blog/tools/xframeoptions/ so at the moment, the only solution is to not use `X-Frame-Options` on the slave domain.

**Comment by brandonparsons** [comment]
Spot on. I removed the `X-Frame-Options` header that my server was returning and it works great.  Thanks!

**Comment by jpillora** [comment]
No worries :)
