### ISSUE TITLE
Proper way to use XDomain together with XHook

### ISSUE THREAD

**Issue by brandonparsons** [jpillora/xdomain#29]
Hi there,

XDomain is working perfectly to allow cross-origin AJAX requests.

I'd also like to use the built-in XHook functionality to stub out some requests to specific routes.  This works fine when the url is local to the source, but not cross-domain.  For example, using the following before_hook:

``` javascript

xhook.before(function(request, callback) {
  if (RegExp("^(.*)/change_password$").test(request.url)) {
    return callback({
      status: 200,
      statusText: "OK",
      text: ' {"message": "Password updated."} ',
      headers: {
        'Content-Type': "application/json; charset=utf-8"
      }
    });
  }
});

```

works fine if I perform an ajax request to `/api/change_password`, but not if I perform one to `http://localhost:3000/api/change_password`.  It would appear that `XHook` is not grabbing requests that are going cross-domain.  I could be doing something wrong though.

**Comment by jpillora** [comment]
Your code is correct. What's happening is XDomain has taken the [first hook and then is hijacking the request before it gets to your hook](https://github.com/jpillora/xhook#overview). It's not documented, though you can specify the hook index when you add your listener, like: `xhook.before(function() {...}, 0)` to explicitly set this hook as the first in the chain.

I'm in progress of a implementing a few features and I'll throw this in the docs when I get a chance.

General JS tip: if you have no variables in your RegExp string, use a literal. So `RegExp("^(.*)/change_password$")` can become `/^(.*)\/change_password$/`

**Comment by brandonparsons** [comment]
Thanks!

This is a pretty cool library. You should be aware that this solves a pretty big pain point with EmberJS.

**Comment by jpillora** [comment]
No worries, yep I've got quite a few ideas for this library https://github.com/jpillora/xhook#xhook just need to find the time...
