### ISSUE TITLE
Problems on saucelabs

### ISSUE THREAD

**Issue by odino** [jpillora/xdomain#31]
Hey @jpillora,

just as a warning / memo: we are trying to run our automated tests on saucelabs but it seems that xdomain makes them fail. No logs, the browser hangs. Removing xdomain solved the issue.

Do you have any hint / advice? 

(@adamquadmon can provide more insights!)

**Comment by jpillora** [comment]
Could you put up a live demo somewhere?

**Comment by odino** [comment]
One of the apps is our mobile website (see namshi.com)

**Comment by jpillora** [comment]
I just released 0.6, upgrade to that and let me know how it goes. If it's still not working, you can now enable debugging `xdomain.debug = true` and paste what you see back here

**Comment by odino** [comment]
thanks for the hustle @jpillora

**Comment by jpillora** [comment]
no worries @odino did this fix it? note, you can also add a `debug="true"` attribute scripts if thats easier

**Comment by jpillora** [comment]
Please reopen if needed
