### ISSUE TITLE
Custom Headers being set before setRequestHeader is populated.

### ISSUE THREAD

**Issue by enrique-ramirez** [jpillora/xdomain#34]
Hello,

I'm not sure if this is a problem with my implementation or a bug that's yet to be noticed. I'm using jQuery and Backbone, in case that matters. My problem is, I need custom headers for my CORS request to work (I send `Accept`, `X-CSRF-Token` and `Authorization` headers, all needed for the API to respond accordingly), but they are not being sent when using xdomain.

After much debugging, I found out xdomain IS receiving the headers, but the `xhr.setRequestHeader()` function seems to be called before the request headers are set.

Being a little more specific, I added two console logs. One right after [this line](https://github.com/jpillora/xdomain/blob/gh-pages/dist/xdomain.js#L280), logging the `userRequestHeaders` object, the other one right after [this other line](https://github.com/jpillora/xdomain/blob/gh-pages/dist/xdomain.js#L317), logging the same object. I then launched my console and I'm seeing the `setValue` function being called BEFORE the switch has been activated (and thus, populated with the custom headers). Here's a screenshot of firebug's output:

![screen shot 2014-01-14 at 5 35](https://f.cloud.github.com/assets/1190640/1916247/d2dfe81a-7d74-11e3-81b1-36bec2150b6e.png)

I saw the examples, and custom headers seem to be being sent just fine on them, so I apologise if this is an issue on my end (and if it is, would appreciate any direction as to where the error might be).

Thanks for your time!

**Comment by jpillora** [comment]
https://github.com/jpillora/xdomain/blob/gh-pages/dist/xdomain.js#L1 that's v0.4.x!

Sorry, I placed that file there a while ago and chose to leave it there after the v0.5.x upgrade, just incase people are still using it. To remove it, I'll need to place a `console.warn` to give developers notice, then remove it after a time.

Anyway, just use 0.5.x and it should work. See https://github.com/jpillora/xdomain#download

**Comment by enrique-ramirez** [comment]
Oh, sorry about that! Didn't realize I was using an old version. Upgrading to v0.5.x fixed it! Thank you!

**Comment by jpillora** [comment]
no worries
