### ISSUE TITLE
Need refresh before working in IE/9

### ISSUE THREAD

**Issue by damacisaac** [jpillora/xdomain#38]
I've added this to my project and it seems to work, except that I need to refresh before any requests succeed. I'm not seeing any errors in the console. On the front end I have: 

```
<script src="http://jpillora.com/xdomain/dist/0.5/xdomain.min.js" slave="http://my-back-end.com/proxy.html"></script>
```

And in the backend: 

```
<!DOCTYPE HTML>
<script src="http://jpillora.com/xdomain/dist/0.5/xdomain.min.js" master="http://my-front-end.herokuapp.com"></script>
```

Any ideas?

**Comment by jpillora** [comment]
Ah dang, I thought IE9 would work since I tested IE8. I haven't got a Windows 7 machine at the moment :( On IE9, when you visit http://jpillora.com/xdomain do you see `{ "DATA": "1" }`? And can you please add a `debug="true"` attribute to **both** scripts and report the output?

**Comment by jpillora** [comment]
Oh and maybe check if XHook is the problem, please let me know if this example works http://jpillora.com/xhook/#vanilla
Expecting:

> example1.txt
> this is the first text file example (example1.txt)
> example2.txt
> thzs zs thz szcznd tzxt fzlz zxzmplz (zxzmplz2.txt)

**Comment by jpillora** [comment]
Ah and I just noticed that your scripts are still at `0.5`, also try upgrading to `0.6` https://github.com/jpillora/xdomain#quick-usage

**Comment by damacisaac** [comment]
I'm testing IE8/9 at http://www.browserstack.com/. With debug="true" in both script tags, I see:

LOG: Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

LOG: Error getting provincesTypeError: Access is denied.

Again, after refreshing a couple of times, the request works. I tried the other two examples in browserstack and they worked.

**Comment by jpillora** [comment]
XDomain logs/errors have "xdomain (<current-origin>)..." prepended, so those are from another library.

The lack of logs leads me to believe that XHook is missing the requests, did you see:

> Note: It's important to include XDomain before any other library. When XDomain loads, XHook replaces the current window.XMLHttpRequest. So if another library saves a reference to the original window.XMLHttpRequest and uses that, XHook won't be able to intercept those requests.

**Comment by damacisaac** [comment]
Still no luck with `0.6`. In chrome I get: 

xdomain (http://frontend.herokuapp.com): failed to parse url: null xdomain.min.js:3
xdomain (http://frontend.herokuapp.com): failed to parse url: views/main.html xdomain.min.js:3
xdomain (http://frontend.herokuapp.com): failed to parse url: views/headers/header.html xdomain.min.js:3
xdomain (http://frontend.herokuapp.com): failed to parse url: views/users/login.html 

Same errors as before in IE9. 

I have the script placed right below `<body>`, except that a facebook script is inserted asynchronously.

**Comment by jpillora** [comment]
so those are the all xdomain logs when it fails? what about after the refresh and it works?

and are there any scripts in `<head>` ?

note, i just pushed a fix for relative urls, `0.6.1`, though I'm not sure if this is the same issue...

**Comment by damacisaac** [comment]
Ah sorry, I missed some logs. Here are the logs when it succeeds:

```
Received message of type object from http:/backend.herokuapp.com, expected a string all.js:56
Received message of type object from http://backend.herokuapp.com, expected a string all.js:56
Received message of type object from http://backend.herokuapp.com, expected a string all.js:56
Received message of type object from http://backend.herokuapp.com, expected a string all.js:56
xdomain (http://backend.herokuapp.com): receive socket: xdomain-a0f0d55d: 'close' xdomain.min.js:3
xdomain (http://backend.herokuapp.com): send socket: xdomain-a0f0d55d: close xdomain.min.js:3
xdomain (http://backend.herokuapp.com): close socket: xdomain-a0f0d55d xdomain.min.js:3
Received message of type object from http://backend.herokuapp.com, expected a string 
```

When it fails, I only get the  `Access denied` error.

I tried testing again in IE9 using `0.6` and it looks like it's working. I'll have to test some more to be sure. Still needs a refresh in IE8

**Comment by jpillora** [comment]
Ah so it's working now in IE9? maybe try clearing the cache in IE8?

**Comment by jpillora** [comment]
Give the newest version a try, please reopen if it's still broken
