### ISSUE TITLE
Is it possible to use this without effecting all XHRs from the page?

### ISSUE THREAD

**Issue by odedbd** [jpillora/xdomain#4]
I am working on a third-party library that could benefit fro musing xdomain, but I can't presume to effect the XHR behavior of the pages hosting my library.

The use case for me would be to be able to use xdomain explicitly, rather than use it as a behind the scenes default. Is that possible?

Thanks for your attention!

**Comment by jpillora** [comment]
XDomain will parse the request URL, if the domain matches a **slave** domain, xdomain will intercept the request and forward it to the iframe proxy, otherwise it **should** let it pass through unaffected.

**Comment by LongLiveCHIEF** [comment]
@jpillora I'm having the same problem with `0.5` and up.  (`.4.x` doesn't work either, but for other reasons).

I get back a 401 unathorized. here are the results:

```
Accept:application/json, text/plain, */*
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Host:website.org
Origin:http://sub.website.org
Pragma:no-cache
Referer:http://sub.website.org/
User-Agent:Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.76 Safari/537.36
Response Headersview source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:content-type, accept, origin
Access-Control-Allow-Methods:ACCEPT, GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin:http://website.org
Content-Length:58
Content-Type:text/html
Date:Thu, 27 Feb 2014 05:33:54 GMT
Server:Microsoft-IIS/7.0
WWW-Authenticate:Ntlm
X-Powered-By:ASP.NET
```

Remove the xdomain script, and it works again.  (but my other service fails)

**Comment by jpillora** [comment]
If you're getting 401 unauthorized then you're successfully receiving results, correct? So is the problem the `Authorization` header not being set?

Can you post your request?

**Comment by LongLiveCHIEF** [comment]
Yeah, I think that's part of it.  There's also an error: `TypeError: Cannot read property 'origin' of null` on `xdomain.js:459` 

```
log("no slave matching: '" + p.origin + "'");  //line 459
```

The first half of my comment above is the request headers.  I'm using angular, so here's my call: 

```
$http({method:'GET', url:'http://website/api/user', withCredentials: true})
```

response/request info using `0.6.0`:

```
Request URL:http://sub.web.org/EUCNET01077/api/user
Request Method:GET
Status Code:401 Unauthorized

Request Headersview source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Host:sub.web.org
Origin:http://local.web.org
Pragma:no-cache
Referer:http://local.web.org/
User-Agent:Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.76 Safari/537.36

Response Headersview source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:content-type, accept, origin
Access-Control-Allow-Methods:ACCEPT, GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin:http://sub.web.org
Content-Length:58
Content-Type:text/html
Date:Thu, 27 Feb 2014 05:51:04 GMT
Server:Microsoft-IIS/7.0
WWW-Authenticate:Ntlm
X-Powered-By:ASP.NET
```

**Comment by jpillora** [comment]
Ah that script error was fixed in `0.6.2` see [Downloads](https://github.com/jpillora/xdomain#download)

**Comment by LongLiveCHIEF** [comment]
Already on to that... swapping to `0.6.2` immediately resolves the `TypeError: Cannot read property 'origin' of null on xdomain.js:459`

**Comment by jpillora** [comment]
Oh and I see you're using `withCredentials` to pass cookies, I think that's missing at the moment. Require the `document.cookies` to be passed across to the iframe then set there

**Comment by jpillora** [comment]
Can you please make a new feature request issue to implement `withCredentials`?

**Comment by LongLiveCHIEF** [comment]
how do I do that?  (also I've tried with all releases from 0.4 up. that's why i had that answer on tap. And yes I will :)

**Comment by jpillora** [comment]
Go here https://github.com/jpillora/xdomain/issues/new

Lots of bugs fixed and many features implemented in latest so its best to stick to that :)

**Comment by LongLiveCHIEF** [comment]
lol... I  meant about the cookie transfer.

**Comment by jpillora** [comment]
Ah well if you want to implement the feature, you'll need to begin with the [xhook source](https://github.com/jpillora/xhook/blob/gh-pages/src/xhook.coffee) and then move onto the [xdomain source](https://github.com/jpillora/xdomain/tree/gh-pages/src). There's a few steps the contributing guide that show you how to build both libs

**Comment by LongLiveCHIEF** [comment]
gotcha.  One more thing to note... the request is being sent as an xhr Request still.  I believe at one point, with one of the versions, it _was_ being pushed through as an XmlHttpRequest, but there was some other error.  There is no proxy definition for that host either.

**Comment by jpillora** [comment]
xhr Request vs XMLHttpRequest? There's only XMLHttpRequest. Older versions
used to send just one request and got one response back. Now it sends and
receives events.

On Thu, Feb 27, 2014 at 5:24 PM, Brian Vanderbusch <notifications@github.com

**Comment by jpillora** [comment]
Ah are you referring to IE's ActiveXObject? or IE's XDomainRequest (CORS)?

On Thu, Feb 27, 2014 at 5:40 PM, Brian Vanderbusch <notifications@github.com

**Comment by LongLiveCHIEF** [comment]
Whatever you're hiding away. It's ironic really.  If I use the script normally (not wrapped in an IE conditional), then IE works for both api's.  (the one discussed here doesn't have a proxy.html file installed because it has CORS headers).

If I wrap it in a conditional tag, then the call to the other domain (with the proxy) fails from Chrome/FF due to lack of CORS support.

Without the script at all, IE and Chrome both have the same ability, to access the api discussed here while failing to pass preflight for the other.

Either through browser configuration or something I can't discern, _IE is able to hit the non-proxy api when chrome can't._... and that's when using the `xdomain.js` lib`.
