### ISSUE TITLE
Using xdomain in conjunction with a MongoLab Instance

### ISSUE THREAD

**Issue by nbarrett** [jpillora/xdomain#41]
Hi Jaime,

I came across your xdomain project when googling for IE9 and angular CORS problems.  What you've done with xdomain  looks pretty neat and looks to solve the problem I am having with some IE9 users on a site that I am running (http://www.kentramblers.org.uk/EKWG/#/walks). The site is an angular application and makes calls to a backend MongoLab instance from within the javascript client. On the first call to the Mongolab instance (on https://api.mongolab.com), 'Error: Access is denied' appears in the IE console. Other browsers (Chrome, Firefox, IE 11 are fine). 

There's something I don't understand in README.md with regard to the master/slave domains. If I want to make calls to the mongolab instance does this mean that https://api.mongolab.com is the slave or the master? I guess if it's either, then this solution wont work as I have no control over creating a proxy on that environment? Or is there still hope for me?

Any advice welcomed please!

Cheers, Nick Barrett

**Comment by jpillora** [comment]
Yep, https://api.mongolab.com is the slave, which means you would indeed need to get a proxy file on that domain which might prove difficult. Though there is hope, I just whipped up an IE CORS polyfill: http://jpillora.com/xhook/example/ie-8-9-cors-polyfill.html. This should work with any library, though take note of the listed **Warnings**.
