### ISSUE TITLE
Update bower and use a directory scheme that is.."friendly"

### ISSUE THREAD

**Issue by fjorgemota** [jpillora/xdomain#45]
Ok..Seems like I am posting too many issues to this project =P

I am testing xdomain project using bower..Ok, but, I when use the version in `dist/xdomain.js`, the version used is very...old (v0.4), and the correct folder is in...`dist/0.6/xdomain.js`. If the expected version is in a folder related to a version, why use tag releases? It seems not very helpful..(tag releases is, but not the folder with the version =P)

Other thing: Seems like a new tag release is needed to bower correctly install the bugfix `v0.6.1`, here, its downloading the version `v0.6`, which is affected by the bug #39 and its not....good.

The solution for all this issue is at all very easy to do. But its good to register these things anyway..

Thanks and sorry for the amount of comments this night =) (and for the poor english, lol)

**Comment by jpillora** [comment]
```
{
  "name": "jpillora/xdomain",
  "version": "0.6.2",
  "main": "dist/0.6/xdomain.js",
  "license": "MIT",
  "ignore": [
    "!dist/0.6/xdomain.js"
  ],
  "dependencies": {},
  "devDependencies": {}
}
```

Sorry I don't really use bower, though I've got a script which auto-generates this bower.json, so the `main` field doesn't work? also the `ignore` field is supposed to exclude all files except `main`. Maybe you can let me know how to fix it :) ? Note: the directory structure will stay the same

**Comment by fjorgemota** [comment]
Ok, ok.

I will work on this at night and make a Pull Request fixing it. By the way, let me know: The script that auto-generates `bower.json` is in this Git repository, right? 

Thanks.

**Comment by fjorgemota** [comment]
Hello.

Reading the code I noted that the script that auto-generates bower.json is not in this repository, but in https://github.com/jpillora/grunt-source-jslib project, as something generic that you manage by using your own project Grunt Source.

Reading the [Bower Spec](https://docs.google.com/document/d/1APq7oA9tNao1UYWyOm8dKqlRP2blVkROYLZ2fLIjtWc/edit#), it say that `ignore` field works as `.gitignore` file works, and, reading the [`.gitignore` spec](https://www.kernel.org/pub/software/scm/git/docs/gitignore.html), it said that lines starting with `!` are included only when all the other fields is removed. Said that..I make a PR that resolves **partially** the problem: https://github.com/jpillora/grunt-source-jslib/pull/1 (see the description to see how to solve completely) =)

That's it. Questions? =)

**Comment by jpillora** [comment]
Hey @fjorgemota thanks for the PR effort, will take a look soon, just pushed `0.6.2` tag which i hope will help

**Comment by jpillora** [comment]
Currently tagged `0.6.5` and includes the new `bower.json`

``` json
{
  "name": "jpillora/xdomain",
  "version": "0.6.5",
  "main": "dist/0.6/xdomain.js",
  "license": "MIT",
  "ignore": [
    "*",
    "!bower.json",
    "!dist/0.6/xdomain.js"
  ],
  "dependencies": {},
  "devDependencies": {}
}
```

**Comment by fjorgemota** [comment]
Yeah!

I tested here with `bower install xdomain` and only the correct files are installed. That's great!

Thanks for accepting the PR =)
