### ISSUE TITLE
Feature Request: Support authorization and transfer of credentials

### ISSUE THREAD

**Issue by LongLiveCHIEF** [jpillora/xdomain#48]
when using the:

```
{
  withCredentials:true
}
```

I'm getting a 401 error.  Removing the `xdomain.js` script immediately clears the error up.

**Comment by jpillora** [comment]
This feature will require the master domains cookies to be passed across to the iframe and set on the slave domain. I may make this feature opt in (`xdomain.passCredentials = true`) as it may introduce some security vulns. Will look into this soon.

**Comment by LongLiveCHIEF** [comment]
probably a good idea.  also, testing shows with IE that the credentials are being passed.

**Comment by LongLiveCHIEF** [comment]
so the "built in" ability is already present when you open an xhr request.  After some research, it's doesn't directly have anything to do with headers, as it's a arg that needs to be passed inside the the `.open()` method itself.  So this could actually be much easier than we're making it out to be.

Although, looks like there will need to be some refactoring of the `facade` xhr object.  I haven't looked through xhook enough times yet to be intimately familiar with both the facade and the original to know for sure what the best way to do this is, but I'm getting there.  Your documentation is very helpful. What may become a problem though:

```
 #==========================
 # Facade XHR
  facade = request.xhr = EventEmitter()

  # progress means we're current downloading...
  facade[ON] 'progress', -> setReadyState 3

  #proxy common events from xhr to facade
  proxyEvents COMMON_EVENTS, xhr, facade 

  if xhook.addWithCredentials
       # initialise 'withCredentials' on object so jQuery thinks we have CORS
        facade.withCredentials = false
```

**Comment by LongLiveCHIEF** [comment]
So I went poking around, because in both instances where you open an xhr instance, you are opening it with `true` for allowing authentication.

However it turns out that the stripping of the authorization headers are actually something that the whole iframe postMessage thing itself will not allow.  So no cookies or Authorization headers are even making it to xhook.

so basically, we'd need an interceptor in the slave that initializes _another_ request from withing the iframe window (can that even be done), and then reads the value of the authorization and cookies headers, and appends them to the request body.

**Comment by jpillora** [comment]
[I've added `withCredentials` to XHook](https://github.com/jpillora/xhook/commit/c2092d1d7ed1e93debe409112c14dc28373099e4), so now you non-xdomain calls should work. I just need to bump XDomain's XHook with new version. 

The `true` in [`open()`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#open%28%29) is the `async` flag, `sync` is not allowed with XHook.

**Comment by LongLiveCHIEF** [comment]
Yeah, discovered that earlier.  I looked into doing a proxy to proxy via synchronous usage of xdomain, but it's not really possible.  I started to look at ways to pass along `Authorization` header while doing that and ran into issues with how `XMLHttpRequest` handles the creation of those headers for cross origin resources.  

with your xdomain, it's not an issue, but that would mean any other requests wouldn't pass along the right credentials for some of the more secure authorization technologies like `NTLM`, which you can't access the token via javascript before the request is actually sent.  Was going to reccommend closing this as a result, as the only possible changes would need to be in [xhook](https://github.com/jpillora/xhook) as you've pointed out.

**Comment by jpillora** [comment]
So the XHook changes are in, though I'm still implementing:

> This feature will require the master domains cookies to be passed across to the iframe and set on the slave domain. I may make this feature opt-in (`xdomain.passCredentials = true;`) as it may introduce some security vulns. Will look into this soon.

**Comment by LongLiveCHIEF** [comment]
I owe you one.  If you take a night off, I'll update and send PR in about 24 hours.

Note: Confirmed for fix in pre-tested non-working environment.

**Comment by jpillora** [comment]
So we have a problem, you can only set cookies inside an iframe if "Allow 3rd Party Cookies" is enabled, many disable this and safari has it disabled by default. So, since we can't use the "Cookie" header, the west thing I can do is set an "XDomain-Cookie" header instead. This would require a middleware of some kind on the server to look for "XDomain-Cookie" and rename it to "Cookie" before doing normal processing.

**Comment by LongLiveCHIEF** [comment]
Yeah, IE10 has similar issues, at least up until a point when they patched it.  That solution _should_ also support IE10.

**Comment by jpillora** [comment]
So the idea of XDomain is to transparently replicate CORS. Since the
problem is a browser setting, it can't be relied on. Therefore it won't
replicate CORS as CORS can be relied on to send Cookies. Best I can do is
the XDomain-Cookie header

On Monday, March 3, 2014, Brian Vanderbusch
<notifications@github.com<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
wrote:

**Comment by jpillora** [comment]
Will close this issue now as I've implemented `XDomain-Cookie` header, which seems to be the only solution. Keep in mind you can still use `withCredentials` with CORS, just not with XDomain. Your other requests (to CORS servers) shouldn't be affected now that the XHook fix is in.
