### ISSUE TITLE
xdomain doesn't work in IE8 if "Enable native XMLHTTP support" disabled

### ISSUE THREAD

**Issue by gotofritz** [jpillora/xdomain#49]
Hi. It seems that xdomain doesn't work in IE8 if "Enable native XMLHTTP support" is disabled in the advanced preferences.

By disabling that, IE relies on MSXML.HttpRequest - I didn't see anything in the code that deals with that, the only reference to ActiveXObjects I found is in `patchClass("ActiveXObject");`

Does xdomain.js support that use case?

Thanks in advance.

**Comment by jpillora** [comment]
Older versions attempted to patch ActiveXObject, I've removed in favour of HTML doctype:

https://github.com/jpillora/xdomain#internet-explorer

**Comment by gotofritz** [comment]
Hi, thanks for the prompt reply, although it doesn't quite answer the question :-)

The doctype has nothing to do with the fact that a user can make window.XMLHttpRequest disappear in IE8 by unticking  "Enable native XMLHTTP support" in the advanced preferences. Then only the ActiveXObject is available, but your code doesn't seem to use it. 

Or am I missing something?

**Comment by jpillora** [comment]
Oh right, well I guess I haven't encountered anyone who has disabled it. I assume this enforced by corporate Windows policy?

**Comment by gotofritz** [comment]
Yep, that's exactly it. I am pretty sure the plugin doesn't deal with that situation, I just got in touch on the off chance I was missing something. If the client insists and we decide to extend the plugin, I'll submit a pull request, otherwise thanks for your time.

**Comment by jpillora** [comment]
Okay, well you should let your client know, XMLHttpRequest has been the standard for about 15 years and is in IE6 and up. Did they have a particular reason for disabling it? Even better they should move off IE though that probably wont happen lol
