### ISSUE TITLE
Getting Access Denied Error at line 3... for all CSS files with AngularJS 1.2.8

### ISSUE THREAD

**Issue by pf-tara-maxwell** [jpillora/xdomain#51]
I've tried placing the XDomain script in various places with no luck. I also just udpated it to the latest.  What is really strange is that my very first API call in the header seems to actually work and pull in data, but then the rest of the page fails and repeatedly gets stuck on the XDomain.js file.
I am on https and all of the cdn script and css references use relative paths (like src="//cdnjs.cloudflare.com/scripts..")
When I check the IE8 web dev console, and 'watch' the s.url param where I'm getting the 'Access Denied' message, it appears to be all of the CSS files.
Also, I am using .Net MVC for the backend with HTML,JS code in both _Layout.html and Index.html, and then all of the other content is pulled in from Angular and partial views.  I tried adding the XDomain script at the very top in the head section of _Layout.html, but then thought that maybe that was why it was trying to 'get' the CSS files through XDomain so I moved it to the Index.html file right above the body content where the ng-app is defined (still above Angular and all of the other JS at the bottom). But I am still getting the same Access Denied errors and the page doesn't load all... it gets 'hung'.

Any thoughts?

**Comment by LongLiveCHIEF** [comment]
This is more than likely an Angular/IE8 problem, or an issue with your css library.  xdomain isn't involved in normal resource loading when the page is being readied.  

My first suggestion, remove xdomain scripts from the page, and see if you still have the same issue.  Eliminate any connection if you can, then start working the rest of it out.

I'm betting it's more than likely an issue with the custom `ng` directives Angular uses.  You have to take special steps to shim IE8 specifically to get it to avoid these types of problems with AngularJS.

**Comment by jpillora** [comment]
@pf-tara-maxwell Are you using HTML5 document type <!DOCTYPE HTML> if not add it and try again, if so, take a look at https://github.com/jpillora/xdomain#troubleshooting

@LongLiveCHIEF [Angular drops support for IE8 in 1.3.x](http://blog.angularjs.org/2013/12/angularjs-13-new-release-approaches.html), @pf-tara-maxwell is on 1.2.8, so I don't think Angular would be the problem...

**Comment by pf-tara-maxwell** [comment]
Thanks so  much for the quick replies!  I am using the HTML5 doctype, and I've checked out the troubleshooting tips.  I'm pretty sure that it isn't an issue with Angular, since we're staying on 1.2.8 for now while we still need to support IE8 and 9.  I am using some shims, too, because of other issues with Angular, Bootstrap and IE.  The ones I'm using are: es5.js, angular-ui-ieshiv.min.js (0.4.0), es5-shim (2.1.0), json3.min.js (3.2.5) and modernizer 2.6.2.  

It seems really odd to me that it throws the 'Access Denied' when the s.url is the twitter bootstrap css, angular css, and ng-grid css all hosted on cdnjs.

**Comment by pf-tara-maxwell** [comment]
So, I swapped out the minified version again to get more specific errors.  I'm getting 'Access Denied' in the console and it is 'breaking' at: xhr.open(request.method, request.url, true, request.user, request.pass);
And when I 'watch' the request.url is shows the first CSS file and when I continue, then it throws 'Unspecified Error' at : xhr.setRequestHeader(header, value);
After a few more of those, it goes back to the xhr.open and throws 'Access Denied' on the next CSS file.  And it continues through the same 'Unspecified Error's, then goes to the next CSS file.  It 'stops' on all 4 of the included CSS files all hosted on CDNs.

Any other ideas?

**Comment by jpillora** [comment]
Access Denied normally happens when there's no slave. Sounds like you have no slave on your CDN? If you're sure you do, then try adding the `debug="true"` attribute to all of your xdomain script tags and copy the console.logs here

**Comment by pf-tara-maxwell** [comment]
I have the slave proxy file on our API server (so that I could hopefully make AngularJS $resource calls from one 'master' subdomain to the 'slave' API subdomain).  But the stylesheets are coming from cdnjs, which I have no control over.  And they are just references in the head section, not pulled in through AJAX or anything.  Why would the stylesheets even go through the xdomain processing?

**Comment by jpillora** [comment]
That is a very good question...

Sounds like its one of your other libraries doing some CSS magic. Hence, very to debug by description alone.

> try adding the debug="true" attribute to all of your xdomain script tags and copy the console.logs here

Is there a live demo somewhere? you could email me the link if it's private

**Comment by jpillora** [comment]
You may also be running into #52 will fix that one soon which may fix your issue

**Comment by pf-tara-maxwell** [comment]
I went ahead and tried modifying the script with the suggestions from #52, but I'm still getting the same errors and then the page just 'hangs'.  
Here's the whole console log:
LOG: xdomain (https://admin-dev01.pf-labs.net): adding slave: https://api.localpf.dev
LOG: xdomain (https://admin-dev01.pf-labs.net): adding slave: http://api.localpf.dev
LOG: xdomain (https://admin-dev01.pf-labs.net): adding slave: https://api-dev01.pf-labs.net
LOG: xdomain (https://admin-dev01.pf-labs.net): adding slave: http://api-dev01.pf-labs.net
LOG: xdomain (https://admin-dev01.pf-labs.net): adding slave: https://api-sandbox.pf-labs.net
LOG: xdomain (https://admin-dev01.pf-labs.net): no slave matching: 'https://cdnjs.cloudflare.com'
  Access is denied.
  xdomain.min.js, line 356 character 7
  Unspecified error.  xdomain.min.js, line 368 character 9
  Unspecified error.  xdomain.min.js, line 373 character 7
LOG: xdomain (https://admin-dev01.pf-labs.net): no slave matching: 'https://cdnjs.cloudflare.com'
  Access is denied.
  xdomain.min.js, line 356 character 7
  Unspecified error.  xdomain.min.js, line 368 character 9
  Unspecified error.  xdomain.min.js, line 373 character 7
LOG: xdomain (https://admin-dev01.pf-labs.net): no slave matching: 'https://cdnjs.cloudflare.com'
  Access is denied.
  xdomain.min.js, line 356 character 7
  Unspecified error.  xdomain.min.js, line 368 character 9
  Unspecified error.  xdomain.min.js, line 373 character 7
LOG: xdomain (https://admin-dev01.pf-labs.net): no slave matching: 'https://s3-us-west-2.amazonaws.com'
  Access is denied.
  xdomain.min.js, line 356 character 7
  Unspecified error.  xdomain.min.js, line 368 character 9
  Unspecified error.  xdomain.min.js, line 373 character 7
LOG: xdomain (https://admin-dev01.pf-labs.net): failed to parse absolute url: ValidateSession
LOG: xdomain (https://admin-dev01.pf-labs.net): failed to parse absolute url: apps/adminconsole/views/customer-home.html
LOG: xdomain (https://admin-dev01.pf-labs.net): proxying request to slave: 'https://api-dev01.pf-labs.net'
LOG: xdomain (https://admin-dev01.pf-labs.net): creating iframe xdomain-b2752cd3
LOG: xdomain (https://admin-dev01.pf-labs.net): new socket: xdomain-a1b9f81b
LOG: xdomain (https://admin-dev01.pf-labs.net): send socket: xdomain-a1b9f81b: request
LOG: xdomain (https://admin-dev01.pf-labs.net): failed to parse absolute url: /apps/adminconsole/views/navigation.html
LOG: xdomain (https://api-dev01.pf-labs.net): adding master: *
LOG: xdomain (https://api-dev01.pf-labs.net): new socket: xdomain-a1b9f81b
LOG: xdomain (https://api-dev01.pf-labs.net): slave listening for requests on socket: xdomain-a1b9f81b
LOG: xdomain (https://api-dev01.pf-labs.net): receive socket: xdomain-a1b9f81b: 'XD_CHECK': '[object Object]'
LOG: xdomain (https://api-dev01.pf-labs.net): ready socket: xdomain-a1b9f81b
LOG: xdomain (https://api-dev01.pf-labs.net): receive socket: xdomain-a1b9f81b: 'XD_CHECK': '[object Object]'
LOG: xdomain (https://admin-dev01.pf-labs.net): receive socket: xdomain-a1b9f81b: 'XD_CHECK': '[object Object]'
LOG: xdomain (https://admin-dev01.pf-labs.net): ready socket: xdomain-a1b9f81b
LOG: xdomain (https://api-dev01.pf-labs.net): receive socket: xdomain-a1b9f81b: 'request'
LOG: xdomain (https://api-dev01.pf-labs.net): request: GET https://api-dev01.pf-labs.net/v1/deploymentenvironments/5eba353b-fb61-4a53-9aa1-42b2cea59443/users/bfd44c58-ff47-4cd4-81f9-1c28415b2aec
LOG: xdomain (https://api-dev01.pf-labs.net): receive socket: xdomain-a1b9f81b: 'XD_CHECK': '[object Object]'
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-a1b9f81b: xhr-event: 'readystatechange'
LOG: xdomain (https://admin-dev01.pf-labs.net): receive socket: xdomain-a1b9f81b: 'xhr-event': 'readystatechange'
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-a1b9f81b: xhr-event: 'readystatechange'
LOG: xdomain (https://admin-dev01.pf-labs.net): receive socket: xdomain-a1b9f81b: 'xhr-event': 'readystatechange'
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-a1b9f81b: response
LOG: xdomain (https://admin-dev01.pf-labs.net): receive socket: xdomain-a1b9f81b: 'response'
LOG: xdomain (https://admin-dev01.pf-labs.net): failed to parse absolute url: /accessrefresh
LOG: xdomain (https://admin-dev01.pf-labs.net): send socket: xdomain-a1b9f81b: close
LOG: xdomain (https://api-dev01.pf-labs.net): receive socket: xdomain-a1b9f81b: 'close'
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-a1b9f81b: close
LOG: xdomain (https://admin-dev01.pf-labs.net): receive socket: xdomain-a1b9f81b: 'close'
LOG: xdomain (https://admin-dev01.pf-labs.net): send socket: xdomain-a1b9f81b: close
LOG: xdomain (https://api-dev01.pf-labs.net): receive socket: xdomain-a1b9f81b: 'close'
LOG: xdomain (https://admin-dev01.pf-labs.net): close socket: xdomain-a1b9f81b
LOG: xdomain (https://api-dev01.pf-labs.net): close socket: xdomain-a1b9f81b
LOG: xdomain (https://admin-dev01.pf-labs.net): close socket: xdomain-a1b9f81b
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-a1b9f81b: xhr-event: 'readystatechange'
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-a1b9f81b: xhr-event: 'load'
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-a1b9f81b: xhr-event: 'loadend'
LOG: tMe9ZyFPDuMgHT8elRCEWJ90n17Z
LOG: xdomain (https://admin-dev01.pf-labs.net): failed to parse absolute url: ValidateSession
LOG: xdomain (https://admin-dev01.pf-labs.net): proxying request to slave: 'https://api-dev01.pf-labs.net'
LOG: xdomain (https://admin-dev01.pf-labs.net): new socket: xdomain-838cc201
LOG: xdomain (https://admin-dev01.pf-labs.net): send socket: xdomain-838cc201: request
LOG: xdomain (https://api-dev01.pf-labs.net): new socket: xdomain-838cc201
LOG: xdomain (https://api-dev01.pf-labs.net): slave listening for requests on socket: xdomain-838cc201
LOG: xdomain (https://api-dev01.pf-labs.net): receive socket: xdomain-838cc201: 'XD_CHECK': '[object Object]'
LOG: xdomain (https://api-dev01.pf-labs.net): ready socket: xdomain-838cc201
LOG: xdomain (https://admin-dev01.pf-labs.net): receive socket: xdomain-838cc201: 'XD_CHECK': '[object Object]'
LOG: xdomain (https://admin-dev01.pf-labs.net): ready socket: xdomain-838cc201
LOG: xdomain (https://api-dev01.pf-labs.net): receive socket: xdomain-838cc201: 'request'
LOG: xdomain (https://api-dev01.pf-labs.net): request: GET https://api-dev01.pf-labs.net/v1/deploymentenvironments/5eba353b-fb61-4a53-9aa1-42b2cea59443/users/bfd44c58-ff47-4cd4-81f9-1c28415b2aec
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-838cc201: xhr-event: 'readystatechange'
LOG: xdomain (https://admin-dev01.pf-labs.net): receive socket: xdomain-838cc201: 'xhr-event': 'readystatechange'
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-838cc201: xhr-event: 'readystatechange'
LOG: xdomain (https://admin-dev01.pf-labs.net): receive socket: xdomain-838cc201: 'xhr-event': 'readystatechange'
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-838cc201: response
LOG: xdomain (https://admin-dev01.pf-labs.net): receive socket: xdomain-838cc201: 'response'
LOG: xdomain (https://admin-dev01.pf-labs.net): failed to parse absolute url: /accessrefresh
LOG: xdomain (https://admin-dev01.pf-labs.net): send socket: xdomain-838cc201: close
LOG: xdomain (https://api-dev01.pf-labs.net): receive socket: xdomain-838cc201: 'close'
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-838cc201: close
LOG: xdomain (https://admin-dev01.pf-labs.net): receive socket: xdomain-838cc201: 'close'
LOG: xdomain (https://admin-dev01.pf-labs.net): send socket: xdomain-838cc201: close
LOG: xdomain (https://api-dev01.pf-labs.net): receive socket: xdomain-838cc201: 'close'
LOG: xdomain (https://admin-dev01.pf-labs.net): close socket: xdomain-838cc201
LOG: xdomain (https://api-dev01.pf-labs.net): close socket: xdomain-838cc201
LOG: xdomain (https://admin-dev01.pf-labs.net): close socket: xdomain-838cc201
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-838cc201: xhr-event: 'readystatechange'
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-838cc201: xhr-event: 'load'
LOG: xdomain (https://api-dev01.pf-labs.net): send socket: xdomain-838cc201: xhr-event: 'loadend'
LOG: xdomain (https://admin-dev01.pf-labs.net): failed to parse absolute url: ValidateSession
LOG: xdomain (https://admin-dev01.pf-labs.net): failed to parse absolute url: apps/adminconsole/views/resource-error.html

**Comment by jpillora** [comment]
Okay from the looks of it, there's a scripts causing Ajax attempts at your
static files. You could put a break point in and look at the call stack to
see which library is making the calls.

**Comment by jpillora** [comment]
Closed until I know more, reopen if needed
