### ISSUE TITLE
xdomain responses do not work well with recent Angular updates due to changes in httpBackend

### ISSUE THREAD

**Issue by bvaughn** [jpillora/xdomain#52]
We've recently discovered a serious IE8/IE9 defect between Angular 1.2.10+ and the xdomain library. Initially I thought it to be an Angular defect and [reported it as a bug](https://github.com/angular/angular.js/issues/6558). After further investigation though I realized that the cause of the issue was the interplay between Angular's [$httpBackend](https://github.com/angular/angular.js/blob/master/src/ng/httpBackend.js) (line 94), the xdomain's initialization of `facade`.

Angular checks for response vs responseText like this:

``` javascript
response = ('response' in xhr) ? xhr.response : xhr.responseText;
```

However, the xdomain lib always initializes a `response` attribute (even if it's null for IE) and so this causes any values in `responseText` data to be overlooked.

Fortunately the fix for this is a simple 2-parter.

1) Line 326: do not initialize response to null.

``` javascript
facade.response = null;
```

2) Change `writeBody` to be more like this:

``` javascript
  writeBody = function() {
    if ( response.hasOwnProperty('text') ) {
      facade.responseText = response.text;
    } else if ( response.hasOwnProperty('xml') ) {
      facade.responseXML = response.xml;
    } else {
      facade.response = response.data || null;
    }
  };
```

**Comment by jpillora** [comment]
Hey @bvaughn thanks for the debugging effort. XHook attempts to perfectly implement XMLHttpRequest2, however as you can see, it's not quite there yet. I've setup a basic saucelabs test for XDomain. Still need to add saucelabs to XHook and add more libraries tests. However time is hard to find >.< Will try to incorporate your fix in soon :)

**Comment by bvaughn** [comment]
No problem @jpillora ! Thanks for supporting this library. It's very handy.

**Comment by bvaughn** [comment]
Dude! Thanks for such a speedy turn-around.

**Comment by jpillora** [comment]
No worries
