### ISSUE TITLE
Success handler fired on aborted request with jQuery 2.x

### ISSUE THREAD

**Issue by boblauer** [jpillora/xdomain#55]
When using xdomain and jQuery 2.x, when a long-running request is aborted (in this case, by navigating away from the page), the `success` handler passed to jQuery is executed, even though it should not be.

I verified this does not happen using jQuery 1.7.2.

**Comment by jpillora** [comment]
Hi @boblauer will look into this when I can

**Comment by jpillora** [comment]
Just made:
http://jpillora.com/xdomain/example/jquery2/
which works, though I just saw "by navigate away". So code is executing after you've closed the tab? hit back? The browser should halt everything...

**Comment by boblauer** [comment]
On your example page, if you set 2 breakpoints in the chrome dev tools, one on `done` and one on `fail`, and then refresh the page before the request is aborted, you'll see that the `done` handler is called.

![image](https://cloud.githubusercontent.com/assets/824632/2748759/c6fd4cea-c7d4-11e3-8981-d7eb1960a831.png)

If you replace the jQuery version with an older version (I tested with 1.7.2), you'll see that the `fail` handler is executed in the same scenario.

**Comment by jpillora** [comment]
Ahh my mistake, will look at this again tomorrow

**Comment by jpillora** [comment]
Ah ha. So you have found indeed found a bug :) http://www.w3.org/TR/XMLHttpRequest/#events I'm emitting both `load` and `loadend` always. Though I should only be emitting `load` on **success**. Adding this to XHook issues...
