### ISSUE TITLE
Compatibility with browserify

### ISSUE THREAD

**Issue by sgtpep** [jpillora/xdomain#57]
`this` is not equal to `window` in browserify. So the solution is to pass `window` explicitly.

See: https://github.com/substack/node-browserify/issues/372, https://github.com/Leaflet/Leaflet/pull/1572.

**Comment by jpillora** [comment]
So I've decided not to put this in as setting the module context to `this` gives the user the ability to decide **where** they want the module to initialize itself (which some users might be doing already - which this would break).I'm about to put this mini-UMD snippet in: 

``` coffeescript
(@define or Object) (@exports or @).xdomain = xdomain
```

which will allow AMD (`this.define(...)`), CommonJS (`this.exports.domain = ...`) and `this.xdomain = ...`

So in short, I suggest you do something like:

``` js
(function() {
// use build tool to place all javascript here
}.call(window));
```

**Comment by jpillora** [comment]
Edit: XDomain actually relies on `this` being window, so I'll call the IFEE with `this` though and directly reference `window` instead of via an argument - which should fix this issue :grinning:
