### ISSUE TITLE
Does xdomain detect CORS support first?

### ISSUE THREAD

**Issue by Francisc** [jpillora/xdomain#58]
Hello,

Do you detect CORS support before rewriting `window.XMLHttpRequest`?
For example, IE9 gets the benefits of this, but IE10 which supports CORS gets the original `XMLHttpRequest` object?

**Comment by jpillora** [comment]
No, XDomain assumes that you're using the iframe proxy **instead of** CORS. This is favourable as all browsers **should** function in the same way. Is XDomain not working in Chrome/FF/etc?

I recently added `enable()` `disable()` functions to [XHook](https://github.com/jpillora/xhook), so if you really want to revert back to CORS, in other browsers you could do:

``` js
if(!/IE[89]/.test(navigator.userAgent)) xhook.disable();
```

**Comment by Francisc** [comment]
Hi Jamie,

It's working on Chrome and Firefox, that's not the issue.
It's just that the problem is with IE9, so I only want to enable this functionality for this particular browsers, and let others use native CORS.

Thanks for your excellent reply.

**Comment by jpillora** [comment]
So it's not working on IE9? My point is, I hope it works in all browsers so
you never need to use CORS

**Comment by Francisc** [comment]
For me, the point is to use web standards of which CORS is part of.
IE9 doesn't support it and so for IE9-only I would like to implement this workaround.

As a sidenote, xdomain needs an HTML file placed on the root of the API server as well right?

**Comment by jpillora** [comment]
Well postMessage is also a web standard, which is all XDomain is really.
Nevertheless, each to their own. Doesn't need to be at the root, just needs
to be on the destination domain. See the GitHub page

**Comment by Francisc** [comment]
That's true. What I meant was postMessage is standard for communication between frames, while CORS is between different servers. But you're right, it's also a standard.

Thank a lot for straighten things out for me.
