### ISSUE TITLE
Does not work in current Firefox

### ISSUE THREAD

**Issue by tgr** [jpillora/xdomain#6]
In FF 23.0.1 the JSON data never appears on the [test page](http://jpillora.com/xdomain). The only error I see in the console seems unrelated: _The character encoding of the HTML document was not declared..._

In Chrome the page works as expected.

**Comment by jpillora** [comment]
FF 22.0 Mac OS X is working, downloading 23 now...

**Comment by jpillora** [comment]
FF 23.0.1 Mac OS X is working also, what OS?

**Comment by tgr** [comment]
Win7. In the Web Console, I see `uncaught exception: Timeout connecting to iframe: http://s3.amazonaws.com` after about 15 seconds. In the network tab, I don't even see the request; same for Firebug. The DOM inspector in the Web Console shows the iframe as loaded, though.

**Comment by jpillora** [comment]
> The character encoding of the HTML document was not declared...

Can't test Win7 ATM, however I'm guessing it's because theres no script type attribute set, which is preventing the script from loading. Could you download `xdomain.js` and do a local test? You can test `localhost` vs `127.0.0.1`. I'll upload a new `index.html` soon...

**Comment by jpillora** [comment]
Working on FF 23.0.1 WinXP

**Comment by jpillora** [comment]
Working on FF 23.0.1 Win7 x64

Could be a regional setting, not sure, I'd try set the `type` attr or may set an HTML content type with a `meta` tag
