### ISSUE TITLE
TypeError: Object expected with angular and IE8

### ISSUE THREAD

**Issue by srijken** [jpillora/xdomain#61]
To repro this problem: visit the example page http://jpillora.com/xdomain/example/angular/ with IE8. It won't load the data, and show "TypeError: Object expected" in the javascript console

**Comment by jpillora** [comment]
I'm using newest angular in that example, which I think drops support for
IE8, can you see which line?

**Comment by srijken** [comment]
It's almost impossible to see where it fails, because of the limited debugging in IE8.

I'm using angular 1.2.10, the example uses 1.2.14

I'm still looking, will post here when I find solutions

**Comment by jtmkrueger** [comment]
This _might_ be related to `xdomain.js` not being loaded before you reference `xdomain`. I had the same problem, and found inlining the entire xdomain script ( :-1: ) got me past this in ie8.

**Comment by jtmkrueger** [comment]
@srijken I'm not able to see this with @jpillora 's example in ie8

**Comment by jpillora** [comment]
Will close this until we know more. Others investigating their own issues, give this example a try http://jpillora.com/xdomain/example/angular and compare it to what you're doing and report findings here :) Reopen if needed
