### ISSUE TITLE
XDomain Breaking FB SDK

### ISSUE THREAD

**Issue by benhodgson87** [jpillora/xdomain#62]
Hey, love this plugin, it's proven a great little workaround, thanks for sharing it.

However, one issue I'm hitting on a current project that uses a Facebook login system is that the Facebook JS SDK uses it's own iframe method for communication in <IE9, but as far as I can tell XDomain appears to also hijack the requests going out to the FB SDK, causing Facebook to throw an error on page load.

```
LOG: Given URL is not permitted by the application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. 
```

The issue goes away if XDomain is removed, but obviously this breaks all other HTTP functionality.

Is there any possible way around this, some way of blacklisting domains that XDomain should not attempt to work it's magic on?

Any help or ideas appreciated.

**Comment by jpillora** [comment]
Hi Ben,

I have a feeling this might be the same problem as https://github.com/jpillora/xdomain/issues/21#issuecomment-35588835 have a read of that thread and try the solution posted there. Basically, I've added code to make jQuery work cross-domain out of the box, though it can break services like MixPanel, Intercom, and possibly FB SDK as they wrongly believe the browser supports CORS.

Let me know how that goes

**Comment by jpillora** [comment]
See https://github.com/jpillora/xdomain#faq--troubleshooting

> https://github.com/jpillora/xdomain#faq--troubleshooting
