### ISSUE TITLE
Page refresh required in ie8 using angular 1.2.6

### ISSUE THREAD

**Issue by jtmkrueger** [jpillora/xdomain#65]
I'm using angular 1.2.6, and on initial load in ie8, I get `TypeError: Object does not support this property or method` in the logs. Refreshing the page gets rid of the issue. I've isolated xdomain as the culprit, because removing the references to it at the top of my page cures the problem. I have a suspicion that it's conflicting with the router, but I'm not sure yet.

**Comment by jpillora** [comment]
Sounds like its the similar to #61 ? I haven't had time to find spin up XP and debug it yet. Can you see which line is throwing?

**Comment by jpillora** [comment]
I updated the [angular example](http://jpillora.com/xdomain/example/angular/) to 1.2.16 (newest) and it seems to work. If I can get a line number or exact cause I'll put a fix in, though until then, will mark as need more info

**Comment by jtmkrueger** [comment]
Yes, your example does work. 

I'm going to do some research today, but am going to tentatively blame some sort of interaction with `ngRoute`. When I load the page, the `#/` is appended to the url, but I get the error mentioned above. Upon refreshing the page that already has the `#/` added, it works correctly.

**Comment by jpillora** [comment]
Ah interesting, does indeed sound like a angular router issue...

**Comment by jpillora** [comment]
Will close this until we know more. Others investigating their own issues, give this example a try http://jpillora.com/xdomain/example/angular and compare it to what you're doing and report findings here :) Reopen if needed
