### ISSUE TITLE
"xdomain" module not loading with RequireJS in JavaScript

### ISSUE THREAD

**Issue by joeattardi** [jpillora/xdomain#66]
There is some code to export xdomain as a module if 'define' is defined:

```
(@define or Object) (@exports or @).xdomain = xdomain
```

Unfortunately, in the resulting JavaScript, which is concatenated with xhook.js, the similar code in xhook comes first. Because this is the first module definition encountered in the file, when requiring xdomain, the resulting object is actually xhook, e.g.

```
require(["xdomain"], function(xdomain) {
    console.log(xdomain);
});
```

The value of xdomain is actually xhook:

```
Object {addEventListener: function, removeEventListener: function, dispatchEvent:  function, listeners: function, on: function…}
```

There seems to be no way to access the xdomain module. Granted, I am new to RequireJS so I might be missing something elementary.

As a quick test, I edited the JavaScript and replaced the module definition with a named module definition:

```
if (typeof define === "function" && define.amd) {
    define("xdomain", [], function() { return xdomain; });
}
```

With this code, the xdomain module is properly passed to the function.

**Comment by jpillora** [comment]
Ah interesting, thanks for looking into this, will fix today :)

**Comment by joeattardi** [comment]
I actually got it _mostly_ working this afternoon. Maybe you know RequireJS better than I, with my ~4 hours' experience :)

The modules load OK, but the problem is that the xdomain module doesn't have access to xhook, so I get a "ReferenceError: xhook is not defined" error. The only way I could get it working was to put a reference to xhook in the `window` object, which is horribly ugly, hackish, and defeats the purpose of using modules.

If you want, I can send a pull request of what I have so far, although the changes are pretty basic I'm sure I'm not saving you any work.

**Comment by jpillora** [comment]
Hey Joe, sorry for the delay, manually merged your fix, and also into XHook :) thanks

**Comment by dmarlow** [comment]
I'm having problems with this. I'm trying to use xdomain within a bookmarklet and some sites have requirejs and this logic

```
 if (typeof define === "function" && define.amd) {
```

causes it to force using require. Would it be possible to allow this to be configurable?

```
 if (typeof define === "function" && define.amd && useRequire) {
```
