### ISSUE TITLE
Question regarding 'FAQ' section

### ISSUE THREAD

**Issue by jas-** [jpillora/xdomain#7]
So after looking over this project (and I like the ideas as it is simple to implement), I feel there is a small problem with your protocol description of the [CORS protocol](http://www.w3.org/TR/cors/) (or rather current working draft).

> On RESTful JSON API server, CORS will send a preflight OPTIONS request on every request except GET, generating superfluous traffic.

However, according to the [latest working draft (section on methods defined as 'simple')](http://www.w3.org/TR/cors/#simple-method)

> It gets slightly more complicated if the resource author wants to be able to handle cross-origin requests using methods other than simple methods. In that case the author needs to reply to a preflight request that uses the OPTIONS method and then needs to handle the actual request that uses the desired method (DELETE in this example) and give an appropriate response. The response to the preflight request could have the following headers specified:

Which would be 'GET, HEAD & POST' methods that do not generate superfluous traffic where the RESTful JSON API server would need to respond to ORIGIN preflight requests on PUT & DELETE requests only.

Does this require a pull request to remedy?

**Comment by jpillora** [comment]
You're right about the HEAD requests, however, I mentioned JSON API server because:

> A header is said to be a simple header if the header field name is an ASCII case-insensitive match for Accept, Accept-Language, or Content-Language or if it is an ASCII case-insensitive match for Content-Type and the header field value media type (excluding parameters) is an ASCII case-insensitive match for **application/x-www-form-urlencoded, multipart/form-data, or text/plain**.

And there's the comprehensible summary on MDN: https://developer.mozilla.org/en-US/docs/HTTP/Access_control_CORS#Simple_requests

So, POST JSON would have a `Content-Type` of `application/json` and many servers depend on the `Content-Type` however, you could get around this by using `text/plain`

PR Away :)

**Comment by jpillora** [comment]
Doing a rewrite of XHook, will add HEAD to the docs once it's done, or I'll accept a PR :)
