### ISSUE TITLE
Upload File in IE8/9 doesn't work

### ISSUE THREAD

**Issue by Capellaro** [jpillora/xdomain#74]
Refering to https://github.com/jpillora/xdomain/issues/73.

I just tried the crossdomain.xml tip. But I am stuck on an error when accessing the server for the upload : 
`SCRIPT445: Object doesn't support this action xdomain.min.js, line 3 character 8458`
Here is my upload function that make a call to my slave server :

```
$scope.onFileSelect = function($files) {
        //$files: an array of files selected, each file has name, size, and type.
        for (var i = 0; i < $files.length; i++) {
            var file = $files[i];
            $scope.upload = $upload.upload({
                url: SETTINGS.urlBackend+'/upload/add', //upload script
                method: 'POST',
                file: file
            }).progress(function(evt) {
                console.log('percent: ' + parseInt(100.0 * evt.loaded / evt.total));
            }).success(function(data, status, headers, config) {
                console.log(data);
                // file is uploaded successfully
                if(data.callback == 'success'){
                    $scope.addAlert("success", data.message);
                    $scope.photo = SETTINGS.urlBackend+'/images/tmp/'+data.fileName;
                }
            }).error(function(data) {
                if(data.callback == 'error'){
                    $scope.addAlert("warning", data.message);
                }
            });
        }
    };
```

I must say that I am testing on IE 9 but I think the problem will be the same on any IE <= 9

I am not 100% sure but it seems the error is happening on this line of xdomain.js _ref = req.headers; looking to the error code and line 8459 of xdomain.min.js above.

**Comment by Capellaro** [comment]
My logs right before the error : 

```
LOG: xdomain (http://accred-front.dev.test.ch): proxying request to slave: 'http://accred.dev.test.ch' 
LOG: xdomain (http://accred-front.dev.test.ch): new socket: xdomain-82bdce07 
LOG: xdomain (http://accred-front.dev.test.ch): receive socket: xdomain-82bdce07: 'ready' 
LOG: xdomain (http://accred-front.dev.test.ch): send socket: xdomain-82bdce07: request 
LOG: xdomain (http://accred-front.dev.test.ch): receive socket: xdomain-82bdce07: 'XD_CHECK': '[object Object]' 
LOG: xdomain (http://accred-front.dev.test.ch): send socket: xdomain-82bdce07: ready 
LOG: xdomain (http://accred-front.dev.test.ch): ready socket: xdomain-82bdce07 (emit #1 pending) 
SCRIPT445: Object doesn't support this action 
xdomain.min.js, line 3 character 8458
```

**Comment by jpillora** [comment]
Can you try with the non-min version?

**Comment by Capellaro** [comment]
I just tried with : 

```
<!DOCTYPE html>
<script src="http://jpillora.com/xdomain/dist/0.6/xdomain.js" master="*"></script>
```

But this is what I get then : 

```
LOG: xdomain (http://accred-front.dev.test.ch): proxying request to slave: 'http://accred.dev21.dev.test.ch' 
LOG: xdomain (http://accred-front.dev.test.ch): new socket: xdomain-cc2c20d0 
LOG: xdomain (http://accred-front.dev.test.ch): receive socket: xdomain-cc2c20d0: 'ready' 
LOG: xdomain (http://accred-front.dev.test.ch): send socket: xdomain-cc2c20d0: request 
LOG: xdomain (http://accred-front.dev.test.ch): receive socket: xdomain-cc2c20d0: 'XD_CHECK': '[object Object]' 
LOG: xdomain (http://accred-front.dev.test.ch): send socket: xdomain-cc2c20d0: ready 
LOG: xdomain (http://accred-front.dev.test.ch): ready socket: xdomain-cc2c20d0 (emit #1 pending) 
SCRIPT445: Object doesn't support this action 
proxy.html, line 1 character 1
```

**Comment by jpillora** [comment]
> Do you know if it will be possible to fix this error?

Possibly, though I can't say from those logs, could you make a demo of this? Or better, debug it and see which line is throwing "Object doesn't support this action"

**Comment by Capellaro** [comment]
Well as I said in my first post, is it possible that the error come from that line : _ref = req.headers;as stated in the error log ?

**Comment by jpillora** [comment]
That must be IE's devtools failing, `req.headers` is just a plain object, you normally see "Object doesn't support this action" on things like `forEach()` `defineProperty()`. I think needs to be stepped through. I can have a look, though I'll need a running demo

**Comment by throrin19** [comment]
I have a problem for ie9 upload file :). sSince this subject is already open, I'll avoid opening another.

I used this jquery upload library : https://github.com/blueimp/jQuery-File-Upload

the request is correctly send except, yes this is the big problem, the file is does'nt send O_o. I think is again the xhr/xdomain problem because it works fine on chrome, ie10, firefox, ...

**Comment by jpillora** [comment]
so i mentioned this to @AlexCapi in an email, file upload using xmlhttprequest requires formdata, which isnt supported on ie8/9, all you can do is using a normal form fullpage submit.

@AlexCapi was trying to using a flash workaround, though i dont see how it'll be able to interact with xdomain if you use flash

**Comment by throrin19** [comment]
jquery-file-upload use iframe-transport plugin. I include that but now ie9 show me a download popup to get the server result O_o. But it's not your library in this case, it's jquery-file-upload

**Comment by jpillora** [comment]
yea so iframe transport wont work with xdomain either, xdomain only patches
the xmlhttprequest object

**Comment by Capellaro** [comment]
Still your Form demo at http://jpillora.com/xdomain/example/formdata/ is not working on IE8/9 when trying to upload anything.

**Comment by jpillora** [comment]
They don't have FormData, so it won't work

**Comment by Capellaro** [comment]
You should specify in the description of your library that upload does not work in IE8 / 9 using XDomain in this case.

**Comment by mabotofu** [comment]
It's possible to upload anything if you can convert the file into base64 string format. Sadly IE8 and 9 don't support File API so it can't load local files but you can use Flash. I've used this http://aymkdn.github.io/FileToDataURI/ and xdomain to successfully upload files without any issues on those browsers. It's far better than iframe hack.

**Comment by jpillora** [comment]
+1

**Comment by jpillora** [comment]
XDomain supports FormData though [IE8&9 do not](http://caniuse.com/#search=formdata). A flash uploader would use the flash's AJAX implementation instead of `XMLHttpRequest`, so XDomain will never work in conjunction with flash.

As @mabotofu points out, you can flash to convert a file to a base64 string, then send that via JS ajax (which XDomain can work with). Will close this for now and suggest @mabotofu's solution as the IE89 file upload workaround.
