### ISSUE TITLE
socket.io xdomain error

### ISSUE THREAD

**Issue by throrin19** [jpillora/xdomain#78]
Hello,
in my project i have a problem with socket.io and your library.

If i activate socket.io, xdomain crash with the **Access Denied** error and the 'no slave matching'.

If i remove socket.io, i have no problem.

Have you an idea of my problem ?

**Comment by jpillora** [comment]
have you looked at https://github.com/jpillora/xdomain#faq--troubleshooting ? is there a demo running anywhere?

**Comment by throrin19** [comment]
Yes. It works fine if i don't try to connect on socket.io.

This is my config : 

client side : 

``` html
<!DOCTYPE html>
<head>
 ...
    <!--[if lte IE 10]>
    <script type="text/javascript" src="js/libs/vendors/xdomain/dist/0.6/xdomain.min.js" slave="http://api.foo.com/v1.1/proxy"></script>
    <script type="text/javascript">
        xdomain.debug = true;
    </script>
    <![endif]-->
</head>
<body>
</body>
</html>
```

server side on /v1.1/proxy : 

``` html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <script src="js/libs/vendors/xdomain.min.js" master="http://client.foo.com"></script>
</head>
<body>
</body>
</html>
```

Client and server side are differents.

this is my expressJS CORS configuration for headers : 

``` javascript
var corsOptions = {
            methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"],
            origin : true
            //credentials: true,
            //allowedHeaders : "X-CSRF-Token, X-Requested-With, Origin, Accept, Accept-Encoding, Accept-Version, Content-Length, Content-MD5, Content-Type, evt-id, api-key, del-all, mod-id"
        };
    this.use(cors(corsOptions));
```

**Comment by jpillora** [comment]
under IE, does socketio use flash for websockets? what
about cross-domain websockets? xdomain only replaces XMLHttpRequest

xdomain doesn't use CORS in anyway, it implements CORS-like functionality
with an alternate method

since im not sure what socketio is doing, im not sure where its going wrong

**Comment by throrin19** [comment]
if user has noo flash player installed, socket.io passed by xhr-poll. 
-   whithout xdomain.js, socket works but $.ajax does not works.
-   with xdomain, $.ajax works but socket.io does not works.

in the ie console (whith xdomain.debug = true and socket.io active) i have this : 

```
Journal : xdomain (http://client.foo.com) no slave matching 'http://api.foo.com:80'
```

**Comment by jpillora** [comment]
Oh that :80 would be causing it mismatch, can you remove it from the URL?

**Comment by throrin19** [comment]
I do not know where it comes from. In the xdomain script i have this on slave : 

```
http://api.foo.com/v1.1/proxy
```

It would be socket.io which would conflict?  This is my client socket.io config : 

``` javascript
App.current.socket = io.connect('http://api.foo.com', {
                'try multiple transports'       : false,
                'transports'                    : [
                    'websocket',
                    'flashsocket',
                    'htmlfile',
                    'xhr-polling',
                    'jsonp-polling'
                ]
            });
```

**Comment by jpillora** [comment]
Okay you could try adding the slave again, though add :80 to second one

**Comment by throrin19** [comment]
it works fine. thanks for your job ;)
