### ISSUE TITLE
Not working on OS X Mavericks

### ISSUE THREAD

**Issue by ghost** [jpillora/xdomain#8]
Hello, I have a strange bug when I run the page, the console say:

Uncaught Timeout connecting to iframe: http://s3.amazonaws.com xdomain.js:598
Frame.readyCheck xdomain.js:598
(anonymous function)

I hope it will help you to fix this bug

**Comment by jpillora** [comment]
Will setup automated testing tomorrow

**Comment by jpillora** [comment]
That errors means the master never heard from the slave iframe, so maybe the `proxy.html` failed to load?

Working on Canary Version 31.0.1625.0 on Mac OS X **10.8.4**

**Comment by jpillora** [comment]
Test with new version in the **Downloads** section, reopen if necessary
