### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by ankur20us** [jpillora/xdomain#85]
I am using this library in the following way, so I have  2 projects of java, 1 as web app project with UI from where I will call one URL hosted on another server to get the JSON as like this

Project No  : 1
   Have a UI to get the json from a link which we will provide via text field, hosted on Tomcat running on port 9080 this is slave:
    In this project I have a <b>proxy.html</b> file with this content as : 
    <pre>
    &lt;!DOCTYPE html&gt;
    &lt;script src="http://jpillora.com/xdomain/dist/0.6/xdomain.min.js" &gt;&lt;/script&gt;
     &lt;script&gt;
         xdomain.slaves({
            'http://localhost:8080/group/v1/docs':'*'
         });
      xdomain.debug = true;
    &lt;/script&gt;
    </pre>

Project No : 2
    The project with the API is running on port 8080, is having the <b>proxy.html</b> as : 
    this is master:
    <pre>
      &lt;!DOCTYPE html&gt;
      &lt;script src="http://jpillora.com/xdomain/dist/0.6/xdomain.min.js" &gt;&lt;/script&gt;
      &lt;script&gt;
        xdomain.masters({
          'http://localhost:9080/try/jsondoc.jsp':'*'
        });
        xdomain.debug = true;
      &lt;/script&gt;
   </pre>

**Comment by jpillora** [comment]
See the FAQ and then read the API, your master / slave listings must be
wrong

**Comment by ankur20us** [comment]
I tried in both ways, kept the proxy html in <b>Project 1</b> with master config and for slave config and vice versa for my <b>Project 2</b>, but the issue remains  the same. Do I have to do any other configurationin Chrome?

**Comment by ankur20us** [comment]
hey, its solved now I am able to get the response, thanks, for this plugin
