### ISSUE TITLE
Adding multiple slave format

### ISSUE THREAD

**Issue by ankur20us** [jpillora/xdomain#86]
Hi, I am able to attach your script, in case of this

<pre>
<code>
     &lt;script src="js/xdomain.js" data-slave="http://10.7.22.28:8080/group/proxy.html"&gt; &lt;/script&gt;
</pre>

</code>

This works, but I want to add more slaves, like using your API as:
<code>

<pre>
    &lt;script&gt;
    xdomain.debug=true;
    xdomain.slaves({
      "http://10.7.22.28:8080/group": "proxy.html"
    });
    &lt;script&gt;
</pre>

</code>

This does not works for single same slave as well, where I am doing wrong?

**Comment by jpillora** [comment]
https://github.com/jpillora/xdomain#xdomainslavesslaves

"http://10.7.22.28:8080": "/group/proxy.html"

**Comment by ankur20us** [comment]
Thanks it worked....:)
