### ISSUE TITLE
XDomain.js causing sporadic delays / timeouts in other code

### ISSUE THREAD

**Issue by ghost** [jpillora/xdomain#87]
I'm running into a problem where the page randomly fails to load a random JavaScript file, which causes the application to fail and not load properly.  It appears to possibly be related to network latency, as this does not appear to happen when the response times are fast.

We currently have a lot of things going on in the page.  In addition to Angular code, we're also using TypeKit for fonts, and a bunch of other external tools, such as Omniture / Adobe Tag Manager, and Online Opinion.  One of these sometimes fails when I load or reload the page.

When I remove the XDomain.js include, this issue goes away.

Can you provide any insight into what XDomain may be doing that is causing this to happen?

Thanks!

Josh

**Comment by jpillora** [comment]
Is the JavaScript file being loaded via XHR?

Also, read **XDomain is interfering with another library!** in the [FAQ](https://github.com/jpillora/xdomain#faq--troubleshooting) and report back
