### ISSUE TITLE
Send the original Host

### ISSUE THREAD

**Issue by Xylez01** [jpillora/xdomain#88]
Hi,

Would it be possible to send the original host in another header?
I gave the `master.coffee` file a look and I think it's possible. I would have tried it myself but my coffeescript knowledge is very small and I have no experience in it.

**Comment by jpillora** [comment]
This has been brought up before, see https://github.com/jpillora/xdomain/issues/47#issuecomment-36507133. Basically, just add the master href into the slave iframe url, then requests from the slave will set a `referrer` header with the master in the url.
