### ISSUE TITLE
InvalidStateError

### ISSUE THREAD

**Issue by btknorr** [jpillora/xdomain#9]
I have my webapp setup correctly according to the docs, but I get the following error when calling my slave:

Uncaught InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable. xdomain.min.js:3
a.(anonymous function).B.(anonymous function) xdomain.min.js:3
Response build.js:3463
(anonymous function) build.js:3607
Emitter.emit build.js:2982
xhr.onreadystatechange build.js:3936
v.trigger xdomain.min.js:3
v.set xdomain.min.js:3
v.deserialize xdomain.min.js:3
(anonymous function) xdomain.min.js:3
(anonymous function) xdomain.min.js:3
a.recieve xdomain.min.js:3
(anonymous function) xdomain.min.js:3

**Comment by jpillora** [comment]
Browser/OS?

**Comment by btknorr** [comment]
Chrome Version 29.0.1547.65 on Mac OS X 10.8.4

**Comment by jpillora** [comment]
That's exactly what I'm running and it's working for me, does the demo page work?

**Comment by btknorr** [comment]
Here is a link to the test we are trying:

http://www.fasterthanmypuppet.com

**Comment by jpillora** [comment]
fixed, _I think_, update xdomain.js and reopen if still broken :)
