### ISSUE TITLE
Does xdomain support File Transfers?

### ISSUE THREAD

**Issue by boroth** [jpillora/xdomain#97]
I'm attempting to transfer a file via FormData (using the [ng-file-upload](https://github.com/danialfarid/angular-file-upload) module for AngularJS), and getting the following error from xdomain (line 834):

`Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window': An object could not be cloned.`

As far as I can tell, ArrayBuffers and Blobs can be sent via the postMessage function (from http://www.w3.org/TR/2012/WD-webmessaging-20120313/#posting-messages), but I don't know enough about the socket api

Here's a sample request I tried to make (it's the `args` variable that's being sent through to postMessage):

```
[
   "xdomain-f4bdbece",
   "request",
   {
      "method":"POST",
      "url":"http://my-local-apimessages/253/notes/mixed",
      "withCredentials":false,
      "headers":{
         "authorization":"Bearer accessToken",
         "context-organization":"myContextOrg",
         "accept":"application/json, text/plain, */*"
      },
      "body":[
         "XD_FD",
         [
            [
               "form[note]",
               ""
            ],
            [
               "form[by_user_id]",
               17
            ],
            [
               "form[media:is_public]",
               1
            ],
            [
               "form[media:enabled]",
               "1"
            ],
            [
               "form[media:name][0]",
               ""
            ],
            [
               "form[media:description][0]",
               ""
            ],
            [
               "form[media:provider][0]",
               "image"
            ],
            [
               "XD_BLOB",
               [
                  "form[media:binary_content][]",
                  null,
                  "Bob's_Burgers_promo.png"
               ],
               {

               },
               "image/png"
            ]
         ]
      ]
   }
]
```

**Comment by jpillora** [comment]
Is this under IE8 and 9? If so see this thread https://github.com/jpillora/xdomain/issues/74#issuecomment-49135969

**Comment by uteq** [comment]
I am having the same problem. This is not in IE8 or IE9. I'm running the current Google Chrome Version 40.0.2214.111 (64-bit).

I simply implemented the angular-file-upload.min.js v3.0.2 module and xdomain.min.js v0.6.17

**Comment by jpillora** [comment]
I'll try debugging it if you can create a live version? You can email me the link if you want to keep it private

**Comment by uteq** [comment]
Thank you! If I'm right, you've received an email.

**Comment by jpillora** [comment]
I did, I just forgot about it! Will check out the link now

**Comment by theRichu** [comment]
Same here :( Any progress?

**Comment by AndrewAskins** [comment]
Hey, just wanted to check to see if there was a fix for this at any point? I'm running into the same issue using dropzone.js with Ember.js and the current version of Chrome. The strange part is I've used dropzone in an ember app before with xdomain and had no issues. Probably means there's a problem with my configuration or something but I'm at a bit of a loss so I thought I'd check.

**Comment by anandaanv** [comment]
Hi.. is this issue solved by any chance?
